casdoor/casdoor

.gitignore
ignore `.swp` files, which may be created by editors like `vim` on linux.
=> .gitignore add ".swp"

object/application.go, object/token.go, routers/authz_filter.go
If there is a client id and a client secret in URL, Casdoor will treat this request as `built-in/service`'s.
=> feat: authorize via clientId and clientSecret

web/src/UrlTable.js, web/src/auth/LoginPage.js
1. Replace `<Link>` to `<a>` because it does not use prop `to` at `LoginPage`
2. Use `index` as key at `UrlTable`
Signed-off-by: WindSpirit <simon343riley@gmail.com>
=> fix: <Link> to <a> and table key

controllers/service.go, controllers/util.go, object/application.go, routers/authz_filter.go, routers/router.go
Deployed at: https://door.chromium.link
admin 123456
Now, programs like Casnode can use Casdoor to send Emails and short messages.
You can send a request in postman like this to test the API:
`POST: https://door.chromium.link/api/send-email?clientId=cdf67a8571cd13a62bcf&clientSecret=98e21c4e25153c556696dd21ca2ff9a23c642751`
POST body:
```json
{
"title":"Email Test",
"content":"Email Test Content",
"receivers":["shiftregister233@outlook.com","211277749@qq.com"],
"sender":"Email Test Sender"
}
```
=> feat: expose email and sms APIs as services to SDK

object/record.go, util/path.go, util/string.go
Deployed at: https://door.leviatan.cn/
Hide meaningless but secure related params in record uri
And fix the error that record uri too long like `accessToken`(access `account` from `Setting` in Header)
=> fix: hide meaningless params in record uri

README.md, web/package.json
Fix: https://github.com/casbin/casdoor/issues/294
Casdoor's front-end is built using yarn. Using npm will cause potential bugs due to installing wrong version of dependencies, so we just ban it.
Use solution from: https://github.com/alexanderwallin/use-yarn-instead/issues/1#issuecomment-292564355
=> feat: ban npm to solve potential bugs

main.go
If perm is not set manually, `go run main.go` cannot even start when `umask=022` because of permission error.
https://github.com/beego/beego/issues/3751
https://github.com/beego/beego/pull/4043
=> fix: log file permission

controllers/account.go
`IsSignupItemEnabled` fails to do what it should do. It just check the existence of an item in `application.SignupItems`. 
But the `SignupItems` will always have all the items, even those items which are not visible or required. So I use `IsSignupItemVisible` instead.
In fact, an item is **actually enabled** only if it is visible, so `IsSignupItemEnabled` is of no use. Can we just remove it?
=> fix: signup logic when email and phone not enabled

web/src/App.js
I think there have no use to display resources and swagger menu.
They should only upload thing through avatar uploading or something administers allow.
And swagger is for developer, normal users needn't see it.
=> refactor: display resources and swagger menu  for normal users

web/src/SelectRegionBox.js, web/src/UserListPage.js
With the update of #321, the data saved in different language interfaces are also in different languages. 
So I tend to save the country code and transfer it to the name when rendering.
Signed-off-by: “seriouszyx” <seriouszyx@foxmail.com>
=> fix: save country code

web/src/auth/LoginPage.js
Display "Continue with (User)" button only if the currently logged-in user is a member of the client's corresponding organization.
Signed-off-by: Lex Lim <hyperzlink@outlook.com>
=> fix: display "Continue with (User)" button of another organization

object/token_jwt.go
fix: fix incorrect issuer in id token of oidc
This modification is proposed according to oidc protocol as well as on demand of users trying to use  casdoor  in oidc
=> fix: fix incorrect issuer in id token of oidc

controllers/token.go, object/token.go
This PR contains 2 fixes: 
1.  add an 'id_token' field in access_token according to oidc protocol
2. supporting read client_id and client_secret from Basic Authorization Header, and return 400 instead of 200 when we cannot give out access_token.
See  <https://code.google.com/p/goauth2/issues/detail?id=31>  for why we are doing this.
This is because that despite Oauth 2.0 (rfc 6749, section 4.1.3)has mentioned that client_id and client_secret should be put into post form when using 'authorization code grant' method, (which is exactly the way we use in casdoor), however there do exist a contradictory expression in the same doc (rfc 6749, section 2.3.1) which is "The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a client …
=> fix: add id_token and support auth header

controllers/util.go, routers/auto_signin_filter.go, routers/base.go
Fix: https://github.com/casbin/casdoor/issues/353
In the OIDC protocol, userinfo_endpoint often uses bearer token to access userinfo. In casdoor,  bearer token method is currently not supported, which makes it difficult to access some services, like Jenkins.
=> fix: support using bearer token to access protected resources

controllers/auth.go, object/provider.go, object/saml.go, web/src/ProviderEditPage.js, web/src/auth/AuthBackend.js, web/src/auth/LoginPage.js
Fix: https://github.com/casbin/casdoor/issues/368
I added an option as below to determine whether to sign the request. If enabled, the certification should be uploaded to Keycloak Clients. I will update the documentation later.
However, there were some troubles during the development process. The gosaml2 lib seems to have some bugs about this point, and I have opened an [issue](https://github.com/russellhaering/gosaml2/issues/89). 
So if enable the option, we will use POST binding instead of Redirect binding. 
When tested with Aliyun IDaaS, the certification management function is VIP. And I can't find an option like `Client Signature Required` in Keycloak. So I suggest disable the option while using Aliyun IDaaS.
=> feat: support AuthnRequest in SAML

controllers/account.go, controllers/auth.go, controllers/token.go, object/token.go, object/token_jwt.go, web/src/auth/AuthBackend.js, web/src/auth/Util.js
Fix: https://github.com/casbin/casdoor/issues/358
1. add nonce parameter.
Some packages  like [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc) verify that the nonce is the same in request and  response, so nonce support needs to be added.
2. add sub in userinfo endpoint.
Some applications need to verify the sub in the userinfo endpoint, so add it. There may be a better implementation later.
=> feat: add OIDC nonce and sub support.

conf/conf.go, controllers/account.go, docker-compose.yml
1. in get-account api, sub should reruen user's id instead of user's name.
2. according to [this document](https://docs.docker.com/compose/compose-file/compose-file-v3/#environment), any boolean values (true, false, yes, no) need to be enclosed in quotes to ensure they are not converted to True or False by the YML parser.
=> fix: wrong sub return and docker-compose boolean value error.

object/token_jwt.go
When the user uses "JWT-Empty", userinfo will not be returned, but since casdoor currently requires name and owner for accessToken authentication, two additional fields are added.
=> fix: adjust the accessToken field

object/oidc_discovery.go, object/token_jwt.go
Fix: https://github.com/casdoor/casdoor/issues/409
1. Add `kid` in JWK and JWT header
2. Use `Tag` as a workaround for user-custom claims in JWT
=> feat: support minio

web/src/Setting.js
Fix: https://github.com/casdoor/casdoor/issues/445
fixed in a initial project, when open premission page, the page will be crash
=> fix: fix permission page can't open

authz/authz.go, controllers/account.go, controllers/base.go, object/oidc_discovery.go, object/token.go, object/token_jwt.go, routers/auto_signin_filter.go, routers/base.go, routers/router.go
Fix: https://github.com/casdoor/casdoor/issues/443
Userinfo endpoint has been implemented according to the [OIDC standard](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse). 
We also need to adjust the uri of the userinfo_endpoint in oidc discovery, but since our current documentation still uses the old get-account endpoint for the integration, e.g. [Jenkins documentation](https://casdoor.org/docs/integration/jenkins/), we need to synchronize the documentation before.
If we use "openid" scope to get userinfo endpoint, we will get like:
```json
{
"sub": "2f80c349-4beb-407f-b1f0-528aac0f1acd",
"iss": "https://door.casbin.com",
"aud": "7a11****0fa2172"
}
```
and if we use "openid profile address phone email", we will get like:
```json
{
"sub": …
```
=> feat: add userinfo endpoint

object/adapter.go, object/application.go, object/cert.go, object/check.go, object/organization.go, object/permission.go, object/provider.go, object/record.go, object/resource.go, object/role.go, object/syncer.go, object/token.go, object/user.go, object/webhook.go
Fix: https://github.com/casdoor/casdoor/issues/439
Solutions:
1. Use prepared statement
2. Implement the black list to filter the `field`
For the request as below:
```
http://localhost:8000/api/get-organizations?p=1&pageSize=10&value=e99nb&sortField=&sortOrder=&field=(updatexml(1,concat(0x7e,(select%20user()),0x7e),1))%20%20and%20name
```
Before:
After:
=> fix: fix the SQL injection vulnerability in field filter

idp/wecom_inter.go
Fix: https://github.com/casdoor/casdoor/issues/441
However, no front-end support has been implemented yet. And wecom's oauth is a little different from the others, 
when we need to get the code, we need to construct the following uri: https://open.work.weixin.qq.com/wwopen/sso/qrConnect?appid=CORPID&agentid=AGENTID&redirect_uri=REDIRECT_URI&state=STATE
`agentid` is  id of an application in Wecom (different from the appid), so we may need to store the application id entered by the user.
=> feat: add wecom internal support

object/token.go, routers/auto_signin_filter.go, util/time.go
In the current version, if we use accessToken for API request, casdoor will only check if the accessToken is issued by itself, but not if the accessToken still exists in the database.
This pr solves the above problem and decouples the accessToken from the identity, so the current code will still work if we support non-jwt accessToken format later.
=> fix: no database check when using accessToken

idp/dingtalk.go, web/src/auth/AuthCallback.js, web/src/auth/Provider.js
According to [this doc](https://open.dingtalk.com/document/orgapp-server/scan-qr-code-to-log-on-to-third-party-websites), the API currently used by Casdoor is listed as outdated.
And the new API can support both scan qrcode and password login.
=> fix: use new dingtalk api and support qrcode method

Dockerfile
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
When I test the Casdoor with the Github provider, I got `Post "https://github.com/login/oauth/access_token": X509 certificate signed by unknown authority`, so I write a Golang project to request this, but I still get the same error. The root cause is the OS doesn't know the correctness of the website ca, so we need to install `ca-certificates` in OS.
=> fix: miss ca-certificates in docker image

util/string.go, util/string_test.go
GetMinLenStr, this function was wrong, it did not always return the smallest number.
The smaller value is returned only its the first item in slice.
Can be tested with
```go
func TestGetMinLenStr(t *testing.T) {
scenarios := []struct {
description string
input       []string
expected    interface{}
}{
{"Should be return casbin", []string{"casdoor", "casbin"}, "casbin"},
{"Should be return casbin", []string{"casdoor", "casbin", "casdoor_jdk"}, "casbin"},
{"Should be return empty string", []string{"a", "", "casbin"}, ""},
{"Should be return a", []string{"a", "casdoor", "casbin"}, "a"},//only test pass because the first works is the smaller
{"Should be return a", []string{"casdoor", "a", "casbin"}, "a"},
{"Should be return a", []string{"casbin", "casdoor", "a"}, "a"},
}
for _, scenery := …
```
=> test: add tests in strings manipulation

controllers/account.go, controllers/auth.go, controllers/token.go, object/oidc_discovery.go, object/token.go, object/token_jwt.go, object/user.go, swagger/swagger.json, swagger/swagger.yml
Since the OIDC Discovery Endpoint will generate an origin based on the request host when the origin is empty in the configuration file, but the accessToken generation and userinfo endpoint do not have this feature yet, so it may return inconsistent iss error in some clients.
=> fix: empty iss return

docker-compose.yml
the casdoor service config in docker-compose.yml has duplicated restart label
=> fix: docker-compose.yml has duplicated label

idp/facebook.go
Fixed an exception caused by "Username" being empty when registering user information when logging in with Facebook.
Signed-off-by: Jerry [lamjerry.johnsken@gmail.com](mailto:lamjerry.johnsken@gmail.com)
=> fix: facebook login exceptions

controllers/token.go, object/application.go, object/token.go, routers/auto_signin_filter.go, web/src/ApplicationEditPage.js
According to [RFC-6749](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4), the following authentication methods have been added.
1. Resource Owner Password Credentials Grant
access `/api/login/oauth/access_token?grant_type=password&username=USERNAME&password=PASSWORD&client_id=CLIENT_ID` to get accessToken
2. Client Credentials Grant
access `/api/login/oauth/access_token?grant_type=client_credentials&client_id=CLIENT_ID&client_secret=CLIENT_SECRET` to get accessToken
3. The application administrator can add or remove allowed authentication methods from the application management page, where the authorization_code method is currently allowed by default. 
The implicit method is not currently supported because it involves front-end modifications.
Signed-off-by: Steve0x2a …
=> feat: add two authentication flow types

controllers/account.go, controllers/auth.go, object/token.go, web/src/ApplicationEditPage.js, web/src/auth/AuthCallback.js, web/src/auth/LoginPage.js
1. add implicit flow support
access `/login/oauth/authorize?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&response_type=token&scope=openid+email+profile&state=1233` to get accesstoken and redirect to `REDIRECT_URI/#token=ACCESS_TOKEN`
2. add id_token response_type support
access `/login/oauth/authorize?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&response_type=id_token&scope=openid+email+profile&state=1233` to get accesstoken and redirect to `REDIRECT_URI/#id_token=ID_TOKEN` 
Fix: https://github.com/casdoor/casdoor/issues/514
=> feat: add implicit flow support

authz/authz.go, controllers/token.go, object/application.go, object/token.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
Fix: https://github.com/casdoor/casdoor/issues/519
Based on [this document](https://openid.net/specs/openid-connect-rpinitiated-1_0.html), the logout endpoint of the token is implemented. Since the Casdoor id_token and access_token are currently the same, we can pass in the access_token and log out the token. 
Now we can get `/api/login/oauth/logout?id_token_hint=ACCESSTOKEN&post_logout_redirect_uri=REDIRECT_URI&state=STATE` to logout token.
But it's a bit strange to have both `login` and `logout` in the endpoint uri, I wonder if anyone has a suggestion for that?
=> feat: add token logout endpoint

authz/authz.go
1. `/api/get-users` , `/api/get-organizations`  can return sensitive information, so only built-in access is allowed.
2. `/api/upload-avatar`, `/api/get-default-providers` are no longer available.
=> fix: update authz rule list

web/src/App.js, xlsx/xlsx_test.go
fix: #542 
previous:
now:
800*600
=> fix: The top-right logout button sometimes disappears for small screen size

routers/auto_signin_filter.go
AutoSigninFilter method only checks for `accessToken` request parameters or `Authorization` request header, doesn't recognize `access_token` request parameters, now added, use `utils.GetMaxLenStr()` method to get the maximum length characters
=> fix: repair the problem that `AutoSigninFilter` middleware doesn't recognize the `access_token` request parameter

controllers/auth.go, controllers/user.go, controllers/verification.go, util/regex.go, util/string.go, web/src/auth/ForgetPage.js, web/src/common/CountDownInput.js
Fix: #554 
After changing to mask phone and email by the backend, the frontend cannot get the real value of phone and email. This will affect 2 APIs, `SendVerificationCode` and `Login()`. 
I use the `name` to store the username on the frontend and pass it to 2 APIs. If the APIs get masked email and phone, they will query the user by the given username to get the real value of email and phone.
=> fix: mask email and phone number on the backend

controllers/account.go, controllers/base.go, web/src/App.js, web/src/auth/PromptPage.js
Fix: https://github.com/casdoor/casdoor/issues/580
Now, after using the accessToken to log in to Casdoor, if you use the logout, you will directly jump to the homepage(if homepage is not empty) of the application that issued the accessToken.
=> fix: redirect for non-built-in app logout

docker-compose.yml
At  `./conf/conf.go:64`, when running in docker, `localhost` is replaced with `host.docker.internal`, however on linux the Docker host cannot be direct access via the `host.docker.internal` hostname. 
The following configuration needs to be added `--add-host=host.docker.internal:host-gateway`.
=> fix: docker-compose up can't work on linux

idp/wecom_internal.go
According to the Wecom official API documentation, Modify GetUserInfo method in order to get the correct user id instead of always the username.
Reference link：https://developer.work.weixin.qq.com/document/path/90196
=> fix: WeComInternalIdProvider GetUserInfo method could not get the correct user id

go.mod, go.sum, idp/alipay.go, idp/provider.go, object/provider.go, object/user.go, web/src/Setting.js, web/src/auth/AlipayLoginButton.js, web/src/auth/LoginPage.js, web/src/auth/Provider.js
Fix: #414
Some points need to be noted is below:
1. The `clientId` of casdoor corresponds to the app_id of Alipay, and the method to create an Alipay app can be found at https://opendocs.alipay.com/open/200/105310
2. The `clientSecret` of casdoor corresponds to the application private key you created on the Alipay open platform. In order to ensure security, Alipay needs us use the private key to generate a signature and send it with the request parameters every time we use its api. 
To geneate the application private key (`clientSecret`) , you can see https://opendocs.alipay.com/common/02kipl. Note that after the key pair is generated, it needs to be configured into the created application according to https://opendocs.alipay.com/common/02kdnc.
3. ~~Since the crypto package in golang does …
=> feat: add Alipay support as idp

controllers/token.go, controllers/types.go
Fix: https://github.com/casdoor/casdoor/issues/637
The accessToken and refreshToken ports now support JSON data in the requestBody.
```json
//test.json
{
"grant_type": "authorization_code",
"client_id": "c58c570b63c9bdbfe00c",
"client_secret": "deabbc5717262b162c2b7235bc32496b05549e87",
"code": "2d17202bef2a1c65cd88"
}
```
use curl:
```bash
curl -v -d @test.json http://localhost:8000/api/login/oauth/access_token
```
=> fix: token endpoint supports json format

object/token.go, swagger/swagger.json, swagger/swagger.yml
Fix: https://github.com/casdoor/casdoor/issues/611
For compatibility reasons, the error message is still in the accessToken, but we may remove it later.
The return value of the token endpoint is now shown below (in case of an error):
```json
{
"access_token": "error: invalid username or password",
"id_token": "",
"refresh_token": "",
"token_type": "",
"expires_in": 0,
"scope": "",
"error": "error: invalid username or password"
}
```
=> fix: add independent error message in token endpoint

controllers/token.go, controllers/types.go
=> fix: fix missing RefreshToken parameter in RefreshToken() API

object/oidc_discovery.go
According to #691 , now add the `alg` and `use` parameters to the response of `/.well-known/jwks`
Fix: https://github.com/casdoor/casdoor/issues/691
=> fix: add 'use' and 'alg' in .well-known/jwks

docker-compose.yml
Hi there, I encountered `docker-compose up` failure when I try to use docker-compose to start casdoor server, indicating "Unknown database 'casdoor'".
Here are the logs:
This is because the server won't create `casdoor` database unless provided with command flag `--createDatabase=true`.
However, the Docker image `CMD` is `./server`, so that server won't create database, which results in `docker-compose up` failure.
https://github.com/casdoor/casdoor/blob/c05fb772241a0f58650a5ed731208303c76580d5/Dockerfile#L37
To fix this issue, we can set `entrypoint` of service casdoor as `/bin/sh -c './server --createDatabase=true'` to make the server create database first.
Here are `docker-compose up` logs after I fixed it:
=> fix: docker-compose up fails

object/application.go, object/organization.go, object/provider.go, object/syncer.go, object/user.go
For now, when editing `Organization`, master password is returned as the masked format `***`, so when clicking `Save` or `Save & Exit` without any change, master password will be updated to `***` or the hash value of `***`.
Similarly, when editing `Provider`, client secret and client secret 2 are both returned `***`, so when saving provider without any change, they will both be updated to `***`.
The solution is to check these columns before updating the record in DB, if they are `***`, then we should `Omit()` these fields.
=> fix: unchanged masked client_secret/password updated to `***`

object/syncer_util.go, web/src/Setting.js
support "+" as below, it will contact the multiple values
=> feat: support "+" in syncer column name

idp/bilibili.go, web/src/common/OAuthWidget.js
Fix: https://github.com/casdoor/casdoor/issues/761
The avatar of bilibili user can't be displayed because of [anti-theft](https://xiaojuzi.fun/pages/8b9f9f/#%E8%A7%A3%E5%86%B3b%E7%AB%99%E9%98%B2%E7%9B%97%E9%93%BE-403).
now:
=> fix: bilibili name and avatar

controllers/auth.go
Querying with username as value may still result in non-unique id of provider.type
=> fix: remove redundant query for OAuth user

object/saml_idp.go
Fix: https://github.com/casdoor/casdoor/issues/798
```xml
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
ID="ONELOGIN_20cf08f88736c7901b6c1b629ec5c53352a0be82"
Version="2.0"
ProviderName="ansible-tower"
IssueInstant="2022-06-14T08:38:05Z"
Destination="http://localhost:8001/login/saml/authorize/admin/awx"
ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
AssertionConsumerServiceURL="http://localhost:8013/sso/complete/saml/"
>
<saml:Issuer>http://localhost:8013/sso/login/saml/?idp=idp</saml:Issuer>
<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
AllowCreate="true"
/>
</samlp:AuthnRequest>
```
=> fix: fix SAML sign element seq error #

.github/workflows/build.yml, Dockerfile, docker-compose.yml, docker-entrypoint.sh, object/init.go, web/src/PermissionListPage.js
+ Build all-in-one image:
```
docker build --target ALLINONE -t casbin/casdoor-all-in-one:latest .
```
+ Build standard image:
```
docker build --target STANDARD -t casbin/casdoor:latest .
```
+ Insert the owner into the url when jumping to the permissions details page.
+ Wrong SignupApplication value causes exceptions in multiple functions for the first admin user, such as uploading avatars, user detail pages, etc.
=> fix: some minor bugs and make Dockerfile more productive.

Dockerfile, docker-entrypoint.sh
Fix: https://github.com/casdoor/casdoor/issues/860
=> feat: fix dockerfile

Dockerfile, docker-entrypoint.sh
This has been fixed in PR: https://github.com/casdoor/casdoor/pull/491 by adding `ca-certificate`. But PR https://github.com/casdoor/casdoor/pull/831 removed these as 
> There are many unnecessary shell commands in the old Dockerfile, such as install ca-certificates && update-ca-certificates. When we use debian:lates or alpine:latest as the base image, /etc/ssl/certs/ca-certificates.crt already contains the latest ca certificates, and we don't need to perform an update operation every time we build.
However, when I test with Github OAuth, `Post "https://github.com/login/oauth/access_token": X509 certificate signed by unknown authority` still raised. I guess default certificate in debain system is out of date. After I added `ca-certificate` again, it works.
=> feat: fix oauth unknown authority in docker

web/src/auth/LoginPage.js
Fix: https://github.com/casdoor/casdoor/issues/921
When `sign up` is false, the footer will not be render, but `code sign in` is in footer and don't be render too. The change is always render footer, then judge separatly if rend `code sign in` and `sign up`.
=> feat: fix 'Enable code sign' is not displayed in the login page

controllers/verification.go, object/organization.go, web/src/UserEditPage.js
This PR fixes the user can reset phone or email without checking `modifyRule` and set the `disabled` property when rendering in the frontend.
=> fix: check reset phone & email modify rules

web/.env
By adding PUBLIC_URL to relative `.`, we can access casdoor's all web pages and static asserts under relative public url.
Closes #933
Signed-off-by: zzjin <tczzjin@gmail.com>
=> feat: Support sub-directory

web/src/ProviderEditPage.js
When change category from other to payment, the type don't follow the change it remains the type before, and it can add success with error type (i.e. `Category: Payment type: Bilibili`), then it lead to provider page error.
=> fix: updateProviderField when add provider payment

object/user.go
If you try to create a user in a non-existent org then panic will occur. This PR fixes this.
Fix: https://github.com/casdoor/casdoor/issues/968
=> fix: panic when creating a user in a non-existent org

authz/authz.go, controllers/application.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml, web/src/backend/ApplicationBackend.js
Fix: #916 
I think use casbin to restrict the permission maybe a little difficult. I add a new api get-organzation-application to resolve the problem. The permissions of normal users to access the  all providers and applications are cancelled.  So far, no side effects.
=> fix: Restrict the request permissions of providers and applications

object/token.go, object/token_jwt.go
Fix: [#899](https://github.com/casdoor/casdoor/issues/899)
Use `owner/name` as jti. It can ensure the uniqueness of jti.
=> fix: add JTI name to JWT token

go.mod, go.sum, web/src/Setting.js, web/src/auth/Provider.js
1. Update go-sms-sender to v0.3.0.
2. Fix: avoid page crash if not found provider info.
Fix: https://github.com/casdoor/casdoor/issues/1002
=> feat: support Mock SMS provider

storage/minio_s3.go, storage/storage.go, web/src/ProviderEditPage.js, web/src/Setting.js
min.io server is compatible with aws s3 interface 🙃
for reference [go code](https://docs.min.io/docs/how-to-use-aws-sdk-for-go-with-minio-server.html)
=> feat(storage): add support for min.io storage

controllers/user.go, object/token.go, object/user.go
Some users reported that the generated token did not contain roles and permissions information. After troubleshooting, it was found that the roles and permissions fields of the user table were empty, and the information of the user table was only used when generating the token, so it was incomplete.
Referring to the implementation in other places, a method to supplement the user roles and permissions information is added in the user.go.
=> feat: fix token info not contains roles and permissions

web/.eslintrc, web/babel.config.json, web/package.json, web/src/BaseListPage.js, web/yarn.lock
Fix: #1071 
- Replace babel-selint with @babel/eslint-parser.The former has been eliminated.
- Update react-scripts and carco version.
- Fix [web/src/BaseListPage.js](https://github.com/casdoor/casdoor/compare/master...conghuhu:cgq?expand=1#diff-ed19bbabf46441685a9abeccb09d1ee752c2cfc2a170bf30aabbda3675a13630) style error.
=> fix: fix hot update error #1071

web/package.json, web/yarn.lock
[webstorm support eslint 8.23.0](https://youtrack.jetbrains.com/issue/WEB-57089/ESLint823-TypeError-thislibOptionsparse-is-not-a-function)
So I change eslint version from 8.23.0 to 8.22.0 and specify precisely.
=> chore: fix eslint error in webstorm

docker-compose.yml
Use MySQL 8.0 instead of specific version, and remove platform as it will use amd64 
mysql image on arm-based system.
=> chore: modify docker compose mysql version

.github/workflows/build.yml
Node.js 12 does not support arm, I upgrade it to the latest lts version.
Also, use GitHub's official cache system for yarn.
=> feat: use nodejs 16 to publish arm docker image

web/src/App.js, web/src/App.less, web/src/auth/LoginPage.js, web/src/auth/SignupPage.js
fix: #1127 
The video show 2 page: 
1. The lod login page. The background image will shrink when narrow the page and in hige resolution screen.
2. The pr login page. The background image always fill the whole window.
And the login form css and background will not take effect to adapt to mobile.
https://user-images.githubusercontent.com/71440988/190973662-90d76c00-5afb-4d03-a992-630cbfe6a350.mp4
=> feat: login background image display

build.sh
I used a DigitalOcean server to build the docker image, which can connect
to Google directly. However, while building, I found it used goproxy for go build.
I think we need to ignore the curl output instead of connect to google twice. This pr fixes it.
=> fix: check whether to use go proxy in build

object/token_jwt.go
Previously, we return an address string in openid jwt payload, which is not meet the spec.
fix #1151
=> feat: fix openid address format

object/adapter.go
Fix: https://github.com/casdoor/casdoor/issues/1169
Using [xorm/migrate](https://gitea.com/xorm/xorm/src/branch/master/migrate) support database version control.
But we still need to handle data migration ourselves, this is because [xorm/migrate](https://gitea.com/xorm/xorm/src/branch/master/migrate) only helps us with schema migration and version control but not data migrations
demo video here:
https://user-images.githubusercontent.com/101162387/195975752-67e30e65-82a2-4b65-a146-b46da873b98e.mp4
=> feat: support database version control

object/avatar.go, object/avatar_test.go, object/syncer_user.go, object/user.go, web/src/CropperDiv.js, web/src/UserEditPage.js
Fix: https://github.com/casdoor/casdoor/issues/1187
Restrict the Intranet ip when download for syncing permanent avatar
Plz review @gregxsunday
=> feat: fix SSRF when download avatar

Dockerfile, build.sh
Previously, `build.sh` was specified to build the binary for the `amd64` platform. It caused that an `amd64` binary was copied to an `arm64` docker image. Therefore, although `arm64` image can be built, the binary cannot run.
This PR fixed this by building two binary and copying the same arch binary to the docker image.
=> feat: fix multi-platform docker image

controllers/util.go, idp/dingtalk.go
Fix: https://github.com/casdoor/casdoor/issues/1231
https://user-images.githubusercontent.com/101162387/197991232-9b42bef2-ce68-40ad-9475-a3b15202b20b.mp4
demo video here
Using the following APIs:
https://open.dingtalk.com/document/orgapp-server/obtain-the-access_token-of-an-internal-app
https://open.dingtalk.com/document/orgapp-server/obtains-the-information-about-the-current-application
=> feat: restrict DingTalk user log in who is under the DingTalk Org(which ClientId belong)

object/init_data.go
Nil array in JSON will be unmarshalled to nil slice in Go. It will cause the front end to crash because it will try to read the length of an `undefined` object.
=> fix: nil error if init data is empty

controllers/account.go, controllers/base.go, controllers/util.go
When I login with the user and password, then bind the WeCom user.
The session stores the WeCom username, But link operation will not create a new user, normally it should be the original username, at this point, can't logout and can't login
=> feat: clear the session of a signin but non-existent user

object/token_jwt_key.go
According to the [official x509 documentation](https://pkg.go.dev/crypto/x509#MarshalPKCS1PrivateKey), the private key generated using `x509.MarshalPKCS1PrivateKey` starts with `-----BEGIN RSA PRIVATE KEY-----` instead of `-----BEGIN PRIVATE KEY-----`.
Otherwise, it will not be parsed by most tools (like OpenSSL, [jwt.io](https://jwt.io/), etc.) because it does not conform to the specification.
=> feat: fix generating wrong x.509 private key file header

web/src/Setting.js, web/src/auth/ForgetPage.js, web/src/auth/LoginPage.js, web/src/auth/PromptPage.js, web/src/auth/SignupPage.js
Fix: #1272 
Original codes failed because:
1. `redirectToLoginPage()` was called in class components which is not compatible with react hooks (`useHistory()` in this case). `redirectToLoginPage()` now uses naive JS implementation of redirecting.
2. `path.join(application.homepageUrl, "login")` returns `login` instead of `/login`.
=> feat: fix the issue of jumping back to the login page after resetting password

web/src/RoleEditPage.js
Fix the crash when the role object domains is null in the on line demo role page
=> fix(RoleEditPage): Fix a crash when the sample role domains is null

object/token_jwt.go
=> fix: Add distinctions between access_token and refresh_token

web/src/auth/AuthBackend.js
Some single page application use hash route mode for the router, which will make all URLs in this application with a character `#`. Currently, the Casdoor front-end sends the redirect URI from application parameters directly without any changes. It will cause the backend side cannot to get the correct redirect URI. 
This commit uses the `encodeURIComponent` function to encode the redirect URI parameters before requesting for the backend. It should help to fix the problem without other side effects.
=> feat: encode redirectUri

object/organization.go
Should return nil if the `organization.DefaultApplication` does exist, or we can't log in to other orgs
see:
=> feat: fix bug in GetDefaultApplication() that caused login error for other orgs

controllers/resource.go, object/avatar.go, object/storage.go
Fix: #1310 
When uploading a new file, check whether the file already exists according to the owner and name fields. If it exists, add "-n" at the end of the file name, and n keeps increasing until there are no duplicates.
=> feat: use another filename when uploading a duplicated file instead of replacing it

web/src/CertEditPage.js
=> fix: responsive certs page editor

web/src/auth/ForgetPage.js
Fix: #1344
Credential sent to backend before the credential has been updated by setState (thus senting the `username` and `name` with the value of `null` to backend at the first time).
=> feat: fix React incorrect usage to fix issue that verification code must be submitted twice to succeed

web/src/SelectRegionBox.js
=> fix: case insensitive country name and country abbreviation search in region selection

controllers/webauthn.go, web/src/auth/LoginPage.js
Fix: https://github.com/casdoor/casdoor/discussions/1377
This bug occurs beacuse we can't get the responseType when using webauthn to sign in. This bug was introduced in PR: https://github.com/casdoor/casdoor/pull/1173/files
The demo video here:
https://user-images.githubusercontent.com/101162387/207065800-18c347ef-ccbf-4ec6-aa4e-84227d52d199.mp4
=> feat: fix sign in error via webauthn

object/permission_enforcer.go
Because of https://github.com/casdoor/casdoor/pull/1357, the policy length become `6`, **so in all model `[policy_definition]` should be the same length now.** 
```ini
[policy_definition]
p = sub, obj, act, "", "", permissionId
```
Fix:
=> feat: fix length of policy and `[policy_define]` in `model`  inconsistent

object/check.go
`break` in line `317` lead to just check AccessPermission in one permissions.
When `allow` is `true` it should return, when `false` it should continue do `for loop(line 297)` to check in other permissions.
=> feat: check AccessPermission in multiple permissions

controllers/auth.go, i18n/locales/de/data.json, i18n/locales/en/data.json, i18n/locales/es/data.json, i18n/locales/fr/data.json, i18n/locales/ja/data.json, i18n/locales/ko/data.json, i18n/locales/ru/data.json, i18n/locales/zh/data.json
Prevent users from logging in with a password through the API when the login with password feature is disabled. 
This enhances security on the backend server.
=> feat: fix login with password bug when feature is disabled

web/src/Setting.js, web/src/SignupTable.js, web/src/auth/LoginPage.js, web/src/auth/SignupPage.js
* Required to accept terms of use in signin page when they are mandatory
* Terms of use are activated only if the rule is set to `Signin`.
=> feat: add terms of use in signin page

web/src/Setting.js
Fix: #1501
Error caused by:
Determine whether the variable is empty before accessing the property.
After Fix:
https://user-images.githubusercontent.com/41513919/215789490-779fec5d-a851-455e-a1e2-a592a27a74a2.mp4
=> fix: remove "Agreement" in application edit page error

object/token.go, util/time.go, util/time_test.go
The wrong format of ExpiresIn makes the result of casdoorsdk.GetOAuthToken (field `expiry`) wrong, too.
`expires_in`: OPTIONAL. Expiration time of the Access Token in seconds since the response was generated.
ref: https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse
in `3.2.2.5.  Successful Authentication Response`
=> feat: change token ExpiresIn to second

controllers/account.go
username is not parsed correctly before deleting the session, now fixed.
=> feat: fix ID parsing bug when calling api/logout

object/permission.go, object/role.go
Once a user login, he can get all the user names in the currently associated permissions or roles from the JWT token.  This might be a security issue IMO.
=> fix(secure): remove user list from roles and permissions field to avoid leaking userlist

go.mod, go.sum, web/src/backend/UserWebauthnBackend.js
Due to the encoding update of challenge to base64url in [WebAuthn v0.6.0](https://github.com/go-webauthn/webauthn/releases/tag/v0.6.0), while webAuthnBufferDecode supports base64, a [bug](https://github.com/casdoor/casdoor/issues/1706) occurred. 
The [previous PR](https://github.com/casdoor/casdoor/pull/1721) temporarily solved this bug by rolling back WebAuthn in go.mod to v0.5.0. This PR updates webAuthnBufferDecode to support base64url encoding in order to use newer versions of WebAuthn. Since it is not yet clear about changes in other APIs, WebAuthn is updated to v0.6.0 in go.mod.
=> fix: update webAuthnBufferDecode to support base64url for WebAuthn updates

Dockerfile
When deployed with docker, the user `casdoor` has no permission to mkdir `tempFiles`, so let's create the folder first.
=> feat: pre-ensure tempFiles folder exists before uploading files

controllers/base.go, controllers/user.go, object/organization.go
If user changes its owner username, the sessionUsername in server will be invalid.  After update user succesfully, if the user modifies its owner username,  setting the sessionUsername with the new username.
Fix: https://github.com/casdoor/casdoor/issues/1790
=> feat: fix function CheckAccountItemModifyRule

web/src/auth/LoginPage.js
Fix: https://github.com/casdoor/casdoor/issues/1793
1. rename "token" to "access_token" #1793 
2. change "?" to "&" #1012 
I will update the relevant document in [casdoor-website](https://github.com/casdoor/casdoor-website) when the PR is merged.
=> feat: make redirectUri token param follow OAuth2 standard

storage/minio_s3.go
Fix: #1813
When set `s3ForcePathStyle = true` the endpoint will be `endpoint/${bucketName}/key` lead the excess `${bucketName}`
https://user-images.githubusercontent.com/41513919/236747989-18299950-45eb-4b71-b419-627ef5c6b891.mp4
=> fix: fix URL path in MinIO storage provider

controllers/enforcer.go, object/permission.go
Fix: https://github.com/casdoor/casdoor/issues/1846
This PR adds param `resourceId` into `POST /api/enforce` API to allow enforce permission based on `resource`. Which will allow other 3rd services or SDK check whether user has permission to access a resource or not.
=> feat: enforce by using resourceId

controllers/user.go
Support get user by userId and owner, support `GetUserByUserId` in casdoor-go-sdk
Currently, it'll panic if you do not provide `id`
https://github.com/casdoor/casdoor-go-sdk/blob/5dcceef2dab9e1b178e97157ab48df49cca7ae17/casdoorsdk/user.go#L274
=> feat: support get user by userId and owner

controllers/user.go, object/organization.go, object/permission.go, object/user.go, web/src/PermissionEditPage.js
feat #1824
The video demonstrates the following:
There are three organizations: `built-in`, `org1`, and `org2`. There are four users: `admin`, `adminSub`, `admin1`, and `admin2`. `admin` is a globalAdmin, `adminSub` is an admin who can manage `org1` and `built-in` organizations, and `admin1` and `admin2` are local admins of `org1` and `org2` respectively.
The access to user page has been modified using the filter approach, and the video demonstrated the CRUD operations of user page. The video showed that the `admin` can manage the user page of all orgs, while the `adminSub` can only manage the user page of `org1` and `built-in`. 
https://github.com/casdoor/casdoor/assets/34300181/14df0860-4808-4847-8355-fc2492310d22
=> ci: add partial admin feature for managing specific organizations

deployment/deploy.go, object/provider.go, object/storage.go, storage/minio_s3.go, storage/storage.go, web/src/ProviderEditPage.js
fix #1974
This pr is related to the previous [one](https://github.com/casdoor/casdoor/pull/1818). The URL path for the MinIO storage provider has two styles, controlled by `s3ForcePathStyle`. When `s3ForcePathStyle` is true, the URL format is endpoint/bucket/xx. When `s3ForcePathStyle` is false, the URL format is bucket.endpoint/xx. To support both styles, users are allowed to modify `s3ForcePathStyle` themselves.
=> feat: add s3ForcePathStyle for storage provider

controllers/util.go
fix to get the correct language from the content of "Accept-Language"
<html><head></head><body>
Accept-Language | zh;q=0.9,en;q=0.8
-- | --
</body></html>
`GetAcceptLanguage` always return `en`
`GetAcceptLanguage` will return the current language
=> fix: fix "Accept-Language" parsing in request

object/user_avatar_favicon.go
`url.JoinPath()` does not work in Go versions before 1.19, for compatibility with older versions, replace it with the previous syntax.
=> feat: remove url.JoinPath() to be compatible with Go 1.17

controllers/enforcer.go, object/permission_enforcer.go
Everytime load enforcer is really time-consuming, instead, we only need load enforcer one time with permissions have the same model and adapter, add list permissionIds as the filter when load enforcer.
=> feat: optimize batch-enforce

object/syncer.go, object/syncer_sync.go, web/src/SyncerEditPage.js
Fix: https://github.com/casdoor/casdoor/issues/1934
When read-only mode is enabled, user info in casdoor will not be synchronized with the source database.
https://github.com/casdoor/casdoor/assets/34300181/ff4327ba-0282-46d2-8c49-e82e88dfbbdd
=> fix: add isReadOnly for syncer

object/syncer_util.go
Modifying a user synchronized by syncer will be blocked. The default value of user.Groups for syncer is nil, while the default value of user.Groups created by the Casdoor front-end is an empty slice with a length of 0. These two JSON parsing results are different, and since the Groups rule is immutable, modification is blocked.
https://github.com/casdoor/casdoor/assets/34300181/ad1ebd6c-4a78-4b3c-a74e-2ab94a070d4d
This PR changes the default value of `user.groups` for syncer to an empty slice with a length of 0.
=> fix: set the default value of user.Groups for syncer

util/path.go
Together with: https://github.com/casdoor/casdoor-website/pull/503
when url.Parse() return nil,err , u.Path would trigger panic
=> feat: fix panic when url.Parse() fails to parse URL

controllers/token.go
The current IntrospectToken response return user Id instead of JWT ID
=> feat: IntrospectToken return the right Jti (JWT ID instead of User Id)

controllers/resource.go
The original pr #2043 seems closed due to misoperation on force-push....  @hsluoyz 
Changes minimized, obey the original logic.
=> fix: /api/upload-resource panics when parsing file_type

object/init.go, web/src/OrganizationListPage.js
Groups should be abled to update by admin that using the sdk to call the API. Now it is imutable, after init Casdoor, the Casnode can not update user because the modify rule.
=> fix: init groups modify rule with admin

web/src/CertListPage.js, web/src/PlanListPage.js, web/src/PricingListPage.js, web/src/SubscriptionListPage.js
we must use a unique rowKey in tables for correctly work of organization filter . But now somewhere we have the name as a key when the name can be the same within different organizations.
=> feat: fix wrong rowKey for tables

controllers/ldap.go, swagger/swagger.json, swagger/swagger.yml
Fix: https://github.com/casdoor/casdoor/issues/2055
As the swagger documentation does not contain a description of the parameters and results for ldap methods,
I add the details.For example:
```go
// GetLdapUsers
// @Title GetLdapser
// @Tag Account API
// @Description get ldap users
// Param	id	string	true	"id"
// @Success 200 {object} LdapResp The Response object
// @router /get-ldap-users [get]
func (c *ApiController) GetLdapUsers() {
......
}
```
=> fix: provide detailed description of ldap in swagger

controllers/user.go, main.go, object/adapter.go, object/group.go, object/user.go, object/user_enforcer.go, web/src/GroupTreePage.js
The pr use casbin store the relationship tetween users and groups, replace the old query statment that using `like` to query users in group.  Note that this commit now does not consider migrating existing user and group relationships into casbin, which would result in users not being found in the organization's group management. I'm not sure if I need to add a migration file before the pr be merged.
The `GroupManager` is not being used now. However, it may then be used to store group hierarchy to determine the inherited permissions of all groups above the user.
Next step, improve the permisson page, support UI to add permission for a group. Because of the implement of using casbin manager user in Casdoor, then we can support the more convenient API, such as `HasPermissionForUser()` to …
=> feat: use the casbin model to store relationships between users and groups

controllers/system_info.go
This fixes a dropped `err` variable in the `controllers` package.
=> fix: dropped controllers err

controllers/cas.go
check pgtUrlObj.Scheme first will cause panic if url.Parse returns error.
=> fix: sendCasAuthenticationResponseErr when pgtUrlObj if not valid url

routers/static_filter.go
Fix: https://github.com/casdoor/casdoor/issues/2269
The error flow is as follows:
Assuming my directory structure is as follows:
```tree
├── GitHub
│   ├── casdoor  # code repository
├── casdoor # compiled binary file
```
Execute the program in the `GitHub` directory:
```bash
./casdoor/casdoor
```
The working directory at this time is `GitHub`.
According to the code:
```go
func StaticFilter(ctx *context.Context) {
urlPath := ctx.Request.URL.Path
/// omitted
path := "web/build"
if urlPath == "/" {
path += "/index.html"
} else {
path += urlPath
}
if !util.FileExist(path) {
path = "web/build/index.html"
}
if !util.FileExist(path) {
return
}
/// omitted
}
```
If the user accesses `/`, according to this code, the returned value is actually `web/build/index.html`. But the current directory is …
=> fix: show error when frontend HTML entry does not exist

controllers/user.go, web/src/UserEditPage.js, web/src/common/modal/PasswordModal.js
When we add a new member to an organization using Casdoor, Casdoor will automatically generate a member with a random username, such as "user_qvducc". When we change the username, for example, to "yunshu", an issue arises where we are unable to successfully edit the password. This is because Casdoor searches for a user based on `owner/username`, and before any changes are saved, the username in the database remains "user_qvducc". However, the frontend uses `orgName/yunshu` instead of `orgName/user_qvducc` to send the request to change the password. As a result, the backend cannot find the user and the password change fails.
=> feat: fix bug that failed to set password after changing username

.github/workflows/build.yml, build.sh
https://github.com/casdoor/casdoor/actions/runs/6324483447/job/17174471503
Building docker image for linux/arm64 takes too long
=> ci: stop building docker image of linux/arm64

object/enforcer.go, object/model.go, object/permission.go
fix: #2373
In order to make as little change as possible, check whether the model meets the requirements of the login policy when the permission editing page is updated, so as to avoid the error of mismatch between the model and the policy during login.
But it cause a new problem, for some user they use the application resource permission not only for UI login check but somewhere else. I'm not really sure what percentage of people use it that way.  Maybe we can add a type specific for UI login check.
=> feat: restrict the model of application type resource permission

controllers/user.go, object/user.go
fix: #2397
This commit will add `GetUserByEmailOnly` and `GetUserByPhoneOnly` so they can be used by the `/api/get-user` endpoint.
=> feat: support calling get-user API by only email, phone or userId without owner

controllers/user.go
=> fix: skip checking old password when the code is provided

controllers/user.go
This fixes several dropped `err` variables that were being dropped in the `controllers` package because `:=` was being used inside an `if` statement.
=> fix: fix dropped errors in GetUser()

ldap/server.go
For example:
```sh
ldapsearch -D cn=admin,ou=built-in,dc=example,dc=com -b ou=xxx,dc=example,dc=com objectClass=posixAccount '*'
```
Should return all these supported properties:
`cn, uid, displayname, email, mail, mobile, title, userPassword`
=> feat: in LDAP, search '*' should return all properties

pp/stripe.go
This fixes a dropped `err` variable in the `pp` package.
=> feat: fix dropped error in stripe.go

manifests/casdoor/Chart.yaml, manifests/casdoor/templates/deployment.yaml, manifests/casdoor/values.yaml
**What**
- Update Helm Chart to support extra containers
**Why**
- Allows multiple containers to run within the pod
**Use Case**
- Needed to add a cloud SQL proxy side car container for GCP (recommended Pattern)
> Note: For connecting from Google Kubernetes Engine, we recommend running the Cloud SQL Auth Proxy in a sidecar pattern, as an [additional container](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_as_a_sidecar) that shares a pod with your application. Also see the related [quickstart](https://cloud.google.com/sql/docs/mysql/connect-instance-kubernetes).  ([GCP Docs](https://cloud.google.com/sql/docs/mysql/connect-auth-proxy))
**How was it Tested**
-  Successfully added side car container without issues
=> feat: helm support extra containers

.github/workflows/helm.yml, manifests/casdoor/Chart.yaml
Fix: https://github.com/casbin/casdoor/issues/2532
**Description**
- Update CI to publish Helm Chart to Docker Hub
**Why**
- Easier onboarding for developers to use casdoor helm chart
- https://github.com/casbin/casdoor/issues/2532
**How**
- CI will package the binary for helm chart before pushing to docker hub
- CI will update the index.yaml that references the binary in docker hub
=> feat: helm release github action

email/http.go, email/provider.go, object/email.go, web/src/ProviderEditPage.js, web/src/Setting.js
Email Webhook provider will send a HTTP request to specific endpoint when casdoor need to send email. This method allow users to handle email by their own will.
=> feat: add custom HTTP Email provider

.github/workflows/helm.yml, manifests/casdoor/Chart.yaml
Fix: https://github.com/casbin/casdoor/issues/2532
**Description**
- Update CI to publish Helm Chart to Docker Hub
**Why**
- Easier onboarding for developers to use casdoor helm chart
- https://github.com/casbin/casdoor/issues/2532
**How**
- CI will package the binary for helm chart before pushing to docker hub
- CI will update the index.yaml that references the binary in docker hub
**How was it Tested?**
- Tested in Forked [Repo](https://github.com/sp71/casdoor/pull/3) and was able to publish to personal [dockerhub](https://hub.docker.com/repository/docker/satindersingh71/casdoor-helm-charts/general)
=> feat: add helm release github action

go.mod, go.sum, object/saml_idp.go
Currently we are using two SAML packages:
1. `github.com/RobotsAndPencils/go-saml` (added in https://github.com/casbin/casdoor/pull/571)
2. `github.com/russellhaering/gosaml2` (added in https://github.com/casbin/casdoor/pull/346)
`github.com/RobotsAndPencils/go-saml` has been officially deprecated and archived by the author on 7 June 2023 [^1]. This PR replaces it with `github.com/russellhaering/gosaml2`.
[^1]: https://github.com/RobotsAndPencils/go-saml?tab=readme-ov-file#unsupported
=> feat: replace deprecated `github.com/RobotsAndPencils/go-saml`

web/src/App.js, web/src/BaseListPage.js, web/src/UserListPage.js
`signup application` is set `app-built-in` for all default users added in web UI. It cause some unmatches in some scenario when getting organization properties by use the signup application of user.
The pr make sure set the `signup application` of added users to fit the current context organization and hidden the organziaton select componet in orgnization tree page because of the duplication and misleadingness.
https://github.com/casbin/casdoor/assets/71440988/b608765c-87ee-4cf5-8083-77a16f7a4796
=> feat: add users with correct application

object/syncer_sync.go
This fixes a dropped `err` variable in the `object` package.
=> feat: fix dropped getAffiliationMap error in object

manifests/casdoor/templates/hpa.yaml
**DESCRIPTION**
- Helm HPA YAML references incorrect apiVersion
- Fix is to apply correct version
- `autoscaling/v2`  uses a different schema for target setting
**HOW WAS IT TESTED?**
- Increased pod count on GCP using this helm chart from 1 to 3 successfully
- Before this change, it would error out
**WHY**
- The beta version was [deprecated](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126) for kubernetes and modern kubernetes engines will error out
=> feat: helm hpa yaml must reference correct apiVersion

manifests/casdoor/Chart.yaml
According to https://hub.docker.com/r/casbin/casdoor/tags and https://github.com/casbin/casdoor/releases latest version is `v1.492.0`
The process can be automated. See https://github.com/casbin/casdoor/pull/2583
=> chore: update helm version to v1.492.0

.gitignore, .vscode/launch.json, Makefile
**Description**
- Add Support to run casdoor in VsCode with debugger
**Why**
- Easier to debug issues and understand codebase with modern debuggers
**How**
- Added makefile command to spin up dependencies via docker
**Testing Changes**
- Ran `make deps` -> Successfully brought up dependencies for casdoor
- VsCode Run and Debug Menu -> Select Start Debugging
- Sent request locally and debugger triggered on breakpoint
**Curl Request**
```
curl localhost:8000/api/health  
{
"status": "ok",
"msg": "",
"sub": "",
"name": "",
"data": null,
"data2": null
}
```
VSCode Debugger
=> fix: add vscode local debugging support

.github/workflows/build.yml
Fix https://github.com/casdoor/casdoor-helm/issues/5
Related https://github.com/casdoor/casdoor-helm/pull/6
Casdoor should commit generated index.yaml to separate helm repo and publish helm package to docker hub. This centralizes the helm publishing workflow logic and ensure the generated index yaml is always committed and in sync with the published docker hub package
=> feat: ci should commit index.yaml and push to docker hub

.github/workflows/build.yml
https://github.com/casdoor/casdoor-helm/issues/9
- Stop manually bumping chart version and instead use generated semantic version
- Syncs versions between casdoor and casdoor-helm-charts
- Add tags to git pushes for casdoor helm chart so it can have releases
=> fix: add semantic versioning for helm charts

idp/provider.go, idp/twitter.go, web/src/auth/Provider.js
Currently, casdoor is unable to log in through Twitter. I have written my own Twitter provider to solve this problem
=> feat: use standalone Twitter OAuth provider instead of goth

object/check.go
Fix the issue where the login error count is not reset to 0 after a successful LDAP user login.
=> fix: fix bug in LDAP user login error count

controllers/application.go, cred/manager.go, cred/sha512-salt.go, object/adapter.go, object/syncer.go, object/token_jwt.go, object/user.go, web/src/OrganizationEditPage.js
Fix #2641 
1. add sha512 encryption support for password
2. extend the length of password to 150
3. add sha512-salt option in the frontend
ScreenShots:
=> feat: Support sha512 password encryption algorithm

util/json.go, util/string.go
Hello! 
Recently i tried to enforce permission with ABAC using 'api/enforce' endpoint. I have model with matchers like this: 
`m = r.sub.Id == r.obj.CreatedBy`
And json body like this:
```json
[
{ "Id": "some-uuid-id" }, 
{ "CreatedBy": "some-uuid-id" },
"delete"
]
```
If i got it right, currently this endpoint cannot handle objects in 'sub' or 'obj' so i implement this simple function to fix this
=> feat: ABAC support for /api/enforce endpoint

object/sms.go, object/sms_custom_http.go, web/src/ProviderEditPage.js
It looks like message templating is not currently supported for the Custom SMS HTTP provider. This PR adds such an opportunity.
=> feat: add template support for Custom HTTP SMS provider

controllers/account.go
The preceding `object.GetOrganization`  can return nil organization causing a panic. Best to handle check gracefully
=> fix: fix /signup organization parameter issue

controllers/account.go
- These error messages were not capturing the authForm values correctly
=> fix: error msg for invalid org & app names in signup

controllers/auth.go, object/provider.go, object/user_enforcer.go
Fix: https://github.com/casbin/casdoor/issues/2681
1. remove unreachable code in object/provider.go
2. add return after call c.ResponseError in controllers/auth.go
3. use error.Is instead of == to check err type in object/user_enforcer.go
=> feat: improve error handling and code format

init_data.json.template, main.go, object/init_data.go, object/init_data_dump.go, object/user.go
Fix: https://github.com/casdoor/casdoor/issues/2606
This pr aims to add data initialization support for 
1. groups
2. adapters
3. enforcers
4. plans
5. pricings
And  support initialize users with group in `init_data.json`
The reason I swapped the initialization order in `main.go` is to ensure that the table `casbin_user_rule` which is initialed by function `object.InitUserManager()` has been successfully created
=> feat: support data initialization for groups, adapters, enforcers, plans and pricings

idp/adfs.go
This picks up a dropped `err` variable in the `idp` package.
=> feat: fix error handling in AdfsIdProvider

idp/goth.go
Seems we have missed VK provider, but it's works with this fix. 
P.S. We already have this provider in supported goth providers list:
https://github.com/casdoor/casdoor/blob/6e28043dba1659e959ef940bf010515c6e5857de/idp/provider.go#L178
=> fix: improve goth code

util/validation.go
Allow dot in the username (like john.smith), which is a corporate standard in many organizations.
=> feat: allow dot in the username (like john.smith)

web/src/Setting.js
fix: fix bug in theme swich
**before**
https://github.com/casdoor/casdoor/assets/47297289/d968d28e-0db6-403c-b638-f7c47acf83bb
**now**
https://github.com/casdoor/casdoor/assets/47297289/2cf2a7d6-36c3-467d-893d-4c7d93a8106e
in previous version ,when you change theme to dark, compact them swich back to default, compact, the compact mode will not take affect
=> fix: fix theme switch bug

web/src/table/ProviderTable.js
You already fixed https://github.com/casdoor/casdoor/issues/2753 but I added a cleaner way to store the default rule for SMS or email provider.
=> fix: Set default value for email and SMS rule to all instead of none

.github/workflows/build.yml, web/src/auth/ProviderButton.js, web/src/common/OAuthWidget.js
feat: use dynamic import to load web3Auth and successfully reduce the size of signIn page to 750KB when web3 idp is disabled
=> feat: use dynamic import to load web3Auth

object/application.go
If the Application is configured with a Captcha Provider, then the /api/get-app-login endpoint needs to return a Captcha type Provider during login. Otherwise, the frontend cannot trigger Captcha during login.
In LoginPage.js, the line 92:const captchaProviderItems = this.getCaptchaProviderItems(this.props.application); 
captchaProviderItems have no Captcha Provider.
=> fix: Ensure /api/get-app-login Returns Captcha Provider for Applications Configured with Captcha

controllers/account.go
In the response of the /api/get-captcha endpoint, add the parameters "owner" and "name" from captcha provider.  because these two parameters will be used when calling the /api/verify-captcha endpoint:
The vform.ApplicationId is composed of owner and name(owner/name).
```
func (c *ApiController) VerifyCaptcha() {
var vform form.VerificationForm
err := c.ParseForm(&vform)
if err != nil {
c.ResponseError(err.Error())
return
}
if msg := vform.CheckParameter(form.VerifyCaptcha, c.GetAcceptLanguage()); msg != "" {
c.ResponseError(msg)
return
}
captchaProvider, err := object.GetCaptchaProviderByOwnerName(vform.ApplicationId, c.GetAcceptLanguage())
if err != nil {
c.ResponseError(err.Error())
return
}
.....
```
=> feat: Add 'owner' and 'name' Parameters to /api/get-captcha Response for /api/verify-captcha Usage

web/src/auth/LoginPage.js
feat: use minWidth for a better display effect in org select  when using chinese or other language which is short to display
before
now
=> feat: use minWidth for a better display effect in org select 

object/init.go, object/init_data.go
Fix: https://github.com/casdoor/casdoor/issues/2885
I think the `Properties` of `AccountItem` is defined for using, so I change the default value of `visible` to `true`. The change of `initDefinedUser` is compatible with old code.
=> fix: fix init data not saved to database (#2885)

.github/workflows/build.yml, Dockerfile, build.sh
Hey, I saw you had support for ARM64 in the past but dropped it because of [performance concerns](https://github.com/casdoor/casdoor/pull/2390).
I optimized the Dockerfile to significantly speed up the ARM64 build process. Now it should only take around the same time as a build just for AMD64. I did that by specifying the `BUILDPLATFORM`. With that, the GitHub runner does not have to emulate ARM64 during the build of the go binaries and the frontend. Beforehand, every step of the Dockerfile was executed twice. The frontend was built on AMD64 and ARM64, as well as the both go binaries. Now, everything is only built once on AMD64.
[Example pipeline run](https://github.com/AlexanderBabel/casdoor/actions/runs/9235557094/job/25410488736)
|                         | Build Time …
=> feat: add back arm64 support in Docker image

web/src/ManagementPage.js
fix: https://github.com/casdoor/casdoor/issues/2995
The non-built-in user interface icons are not fully displayed because the top bar is set to 280px. Setting it to 300px allows for perfect display without affecting other items.
=> feat: fix the top Navbar UI is broken issue

controllers/account.go, object/init.go, object/organization.go, web/src/OrganizationEditPage.js, web/src/locales/ar/data.json, web/src/locales/de/data.json, web/src/locales/en/data.json, web/src/locales/es/data.json, web/src/locales/fa/data.json, web/src/locales/fi/data.json, web/src/locales/fr/data.json, web/src/locales/he/data.json, web/src/locales/id/data.json, web/src/locales/it/data.json, web/src/locales/ja/data.json, web/src/locales/kk/data.json, web/src/locales/ko/data.json, web/src/locales/ms/data.json, web/src/locales/nl/data.json, web/src/locales/pl/data.json, web/src/locales/pt/data.json, web/src/locales/ru/data.json, web/src/locales/sv/data.json, web/src/locales/tr/data.json, web/src/locales/uk/data.json, web/src/locales/vi/data.json, web/src/locales/zh/data.json
Adds the possibility to use the email address as the username if the username field is not visible at signup.
The option can be checked at the organization level.
closes #2756
=> feat: support "Use Email as username" in org

web/src/PermissionEditPage.js
Fix: https://github.com/casdoor/casdoor/issues/3034
After clicking the Save button, the frontend will send an update request. After the first update request, the backend has updated the data in the database but the frontend has not synchronized the organizationName field.
This causes the frontend to send outdated messages to the backend in subsequent changes. The backend cannot obtain the permission record based on the outdated message, so the return value is "unaffected"
=> feat: fix bug in permission's owner edit

object/permission.go, web/src/PermissionEditPage.js
Fix: https://github.com/casdoor/casdoor/issues/3025
When a permission is deleted or the adapter attribute of the permission is changed, the program will determine whether the adapter data table that originally stored the permission is empty after the permission is deleted. If it is empty, the data table will be dropped. 
Although this operation saves storage space, it requires additional DROP permissions, which limits the application scenarios of Casdoor.
=> feat: don't drop empty table for adapters

object/organization.go, web/src/App.js, web/src/OrganizationEditPage.js, web/src/OrganizationListPage.js, web/src/TourConfig.js
Fix: https://github.com/casdoor/casdoor/issues/3026
The enable tour switch has been added to the organization edit page to configure whether the tour is displayed when the organization's users log in.
The tour logo will use the organization logo instead of default logo.
=> feat: use orgnization logo as tour logo and allow to configure whether to enable tour in organization edit page

idp/lark.go
Fix: https://github.com/casdoor/casdoor/issues/3045
This feature enable getting lark phone number when an user signup with lark.
=> feat: OAuth provider lark supports getting phone number

web/src/App.js, web/src/TourConfig.js
Add an extra field "isOrgTourVisible" in localStorage to represent the enableTour attribute in the organization configuration.
At the same time, the condition for judging whether the tour is displayed is changed to localStorage.isOrgTourVisible && localStorage.isTourVisible, which implements the addition of enableTour judgment through localStorage.isOrgTourVisible on the original basis.
=> feat: fix the problem of abnormal tour when refreshing

controllers/system_info.go
Fix: https://github.com/casdoor/casdoor/issues/2981
The docker container does not contain the Git repository, which causes the program to get the version information through Git to report an error.
The original processing program will directly return the exception information after Git reports an error, causing the program to be unable to use the version_info.txt file to obtain the correct version information.
So the program's exception handling logic is changed to: the program returns the exception information only when Git throws an exception and the file fails to obtain the version information.
=> feat: fix bug in obtaining Casdoor version in Docker

ldap/server.go
Fix: https://github.com/casdoor/casdoor/issues/3032
Added needed parameters so that the internal LDAP server can redirect to other LDAP sources correctly and not run into the "wrong credentials" error every time.
Unsure if this is the best way of going about it, so feel free to edit this accordingly. I have tested it on an internal server and it works - for both local and LDAP-synced users. This should not break any existing logic with how little is changed.
=> feat: fix isPasswordWithLdapEnabled logic in handleBind() for redirecting to other LDAP sources

web/src/AdapterListPage.js, web/src/ApplicationListPage.js, web/src/CertListPage.js, web/src/EnforcerListPage.js, web/src/GroupListPage.js, web/src/InvitationListPage.js, web/src/ModelListPage.js, web/src/OrganizationListPage.js, web/src/PaymentListPage.js, web/src/PermissionListPage.js, web/src/PlanListPage.js, web/src/PricingListPage.js, web/src/ProductListPage.js, web/src/ProviderListPage.js, web/src/ResourceListPage.js, web/src/RoleListPage.js, web/src/SessionListPage.js, web/src/SubscriptionListPage.js, web/src/SyncerListPage.js, web/src/TokenListPage.js, web/src/TransactionListPage.js, web/src/UserListPage.js, web/src/WebhookListPage.js
This PR addresses an issue where the page did not refresh correctly after deleting an item from the list, leading to a scenario where the pagination displayed an empty page if the deleted item was on the last page.
- Updated the `delete` method to call the `fetch` function after a successful delete operation.
- Added logic to adjust the current page if deleting an item causes the page to become empty.
This ensures that the table displays the correct data and pagination state after an item is deleted.
- Corrected page refresh issue after item deletion (pagination showing empty pages).
- fix: #3118
=> feat: Pagination not updating after last item deletion

web/src/ProviderEditPage.js
The Storage Provider - "Google Cloud Storage" not allow custom Domain, it will always set the Endpoint value to Domain and I can't change it. https://github.com/casdoor/casdoor/blob/9b9a58e7ac2e27486dd90ee9ce290dfbdef9ffc1/object/storage.go#L120
Currently, I get error when uploading file to GCS, the fileUrl (= provider.Domain + filePath) response not include the bucket name, but I can't change the provider.Domain.
=> feat: allow custom Domain of Google Cloud Storage Provider

object/storage.go
Related to https://github.com/casdoor/casdoor/pull/3128 , we need to add bucket name to the fileUrl with "Google Cloud Storage" Provider and rimPrefix "/" before delete GCS object
=> feat: add provider.Bucket to fileUrl response and TrimPrefix "/" before delete GCS object

captcha/provider.go, web/src/Setting.js, web/src/common/CaptchaWidget.js
fix: https://github.com/casdoor/casdoor/issues/3122
Add reCAPTCHA v3 to the provider type and change the previous type reCAPTCHA to reCAPTCHA v2.
The backend verification logic of google reCAPTCHA v3 and v2 is the same, so the backend code is not modified. Only the captcha operation code is added to the frontend for the v3 version.
=> feat: support reCAPTCHA v3 captcha provider

web/src/CertEditPage.js
fix: certEditPage will be redirected to 404 when change name due to setState is an async function, and certName hasn't update when execute getCert()
**Before**
https://github.com/user-attachments/assets/a94013b5-4e4d-4b7f-acac-8ba1853c01fe
**After**
https://github.com/user-attachments/assets/8da577bf-5219-403c-add3-7904a60898a7
=> feat: certEditPage will be redirected to 404 when name is changed

object/check.go
fix: #3174 
now casdoor will prioritize the use of password set by user in casdoor and use ldap password when users never change their password or use ldap signin method to login
=> feat: Users added through LDAP cannot log in using the set password

routers/static_filter.go
Fix: https://github.com/casdoor/casdoor/issues/3218
add logic for getWebBuildFolder() function
=> feat: add condition for getWebBuildFolder function 

web/src/auth/Obfuscator.js
Fix: https://github.com/casdoor/casdoor/issues/3300
The bug was introduced by PR: https://github.com/casdoor/casdoor/pull/3260
1. In User Management -> Organizations, set the Password Obfuscator to a non-Plain type.
2. In Authentication -> Applications, set the Organization to the one configured in step 1.
3. Use http://host/login/oauth/authorize?client_id=2.application&... for authentication and log in using a password.
=> feat: fix bug that fails to login when PasswordObfuscator is enabled

object/user.go
If I am creating user with API like
```curl
curl --request POST \
--url https://casdoor.example/api/add-user \
--header 'Accept: application/json' \
--header 'Authorization: Basic <...>' \
--header 'Content-Type: application/json' \
--data '{
"phone": "79217210133",
"name": "79217210133",
"owner": "b2cOrg",
"properties": {
"is_synced": "false"
}
}'
```
Property `created_time` is not set
=> feat: set created time if not presented in AddUser() API

web/src/ProviderEditPage.js
allow Qiniu Provider to edit the Domain property in the edit page. I don't know why it's excluded in the first place, but being able to edit it will fix #3310.
Fix: https://github.com/casdoor/casdoor/issues/3310
=> feat: show Domain field for Qiniu storage provider

controllers/casbin_api.go, routers/router.go
Part of: https://github.com/casdoor/casdoor/issues/3206
The casbin-go-cli command should be placed in the casdoor directory.
The request example is:
The result is "Allowed\n"
=> feat: add Casbin CLI API to Casdoor

object/saml_idp.go, web/src/auth/Util.js
fix: unable to get samlRequest from query, in some case samlRequest will not be compressed, samlRequest lost `+` during post
`if strings.Contains(string(defated), "xmlns:")` is used to check whether samlRequest is compressed
=> fix: fix several bugs in samlRequest

.github/workflows/build.yml
v3 of `actions/upload-artifact` and `actions/download-artifact` will be fully deprecated by **5 December 2024**. Jobs that are scheduled to run during the brownout periods will also fail. See:
1. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
2. https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/
=> feat: update CI's `upload-artifact` and `download-artifact` actions to v4

controllers/token.go
fix: #3398 
my fault, according to [RFC7662 SECTION 2.2](https://datatracker.ietf.org/doc/html/rfc7662#section-2.2) token type in introspectionResponse should be `Bearer` or `MAC` which defined in [RFC6749 SECTION 7.1](https://datatracker.ietf.org/doc/html/rfc6749#section-7.1)
@hadestructhor plz help me to test
=> feat: fix issue that introspectionResponse uses `Bearer` instead of raw tokenType

object/user.go
When i update user i only know his login. So I don't want to make additional `GET user` request to find out this user's ID.
=> feat: can pass empty user id on user update

object/get-dashboard.go
Part of: https://github.com/casdoor/casdoor/issues/3455
a simple solution, better solution is on the way
=> feat: only fetch created_time field to reduce data size in get-dashboard API

object/saml_idp.go, web/src/auth/AuthCallback.js, web/src/auth/LoginPage.js
fix:saml redirectUrl may already contains ?, uses & in that case. change response method to POST ProtocolBinding == urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST.
=> feat: fix SAML's redirectUrl and POST ProtocolBinding

authz/authz.go, controllers/cli_downloader.go, main.go, routers/router.go
fix: https://github.com/casbin/casbin-editor/issues/228
Add an automatic CLI tools downloader and updater for Casdoor, supporting Go, Java, and Rust CLI tools across different platforms (Windows, macOS, Linux) and architectures (x86_64, arm64).
- Auto-download CLI tools on application startup
- Periodic updates (every hour) to keep CLI tools up-to-date
- Cross-platform support
- Multi-architecture support
- Provide /api/refresh-engines interface
=> feat: add CLI tools auto-downloader and updater

pp/airwallex.go
Description:
- If the string is shorter than 32 characters, it will be padded with \u0000.
- The descriptor field must not contain null characters.
I'm sorry for not noticing this exception earlier. 😔
=> feat: fix bug due to null characters in descriptor when creating a payment intent

object/token_jwt.go, object/token_standard_jwt.go
Added the `azp` (Authorized Party) claim to various JWT token structures including Claims, ClaimsShort, ClaimsWithoutThirdIdp, and ClaimsStandard.
Because go-jwt refused to add `azp` to standard claim, see golang-jwt/jwt#366
Fix: https://github.com/casdoor/casdoor/issues/3566
=> feat(jwt): add `azp` claim to ID token

email/provider.go, email/sendgrid.go, web/src/ProviderEditPage.js
Fix: https://github.com/casdoor/casdoor/issues/3575
SendgridEmailProvider support dynamic host/path, add From name field
Before:
After:
Sendgrid client init example: https://github.com/sendgrid/sendgrid-go/blob/16f25e4d92886b2733473a19977ccf1aa625a89b/examples/mail/mail.go#L51-L53
=> feat: update SendgridEmailProvider to support dynamic host/path, add From name field

web/src/auth/LoginPage.js
This PR is a continuation of previous PR https://github.com/casdoor/casdoor/pull/3583 and include the same fix in different login flows.
=> feat: Update signinUrl storage to include pathname and query parameters only to prevent new tab popup after password reset

init_data.json.template
Fix: https://github.com/casdoor/casdoor/issues/3619
current init data is unmatch with the struct Group: 
```golang
type Group struct {
Owner       string `xorm:"varchar(100) notnull pk" json:"owner"`
Name        string `xorm:"varchar(100) notnull pk unique index" json:"name"`
CreatedTime string `xorm:"varchar(100)" json:"createdTime"`
UpdatedTime string `xorm:"varchar(100)" json:"updatedTime"`
DisplayName  string   `xorm:"varchar(100)" json:"displayName"`
Manager      string   `xorm:"varchar(100)" json:"manager"`
ContactEmail string   `xorm:"varchar(100)" json:"contactEmail"`
Type         string   `xorm:"varchar(100)" json:"type"`
ParentId     string   `xorm:"varchar(100)" json:"parentId"`
ParentName   string   `xorm:"-" json:"parentName"`
IsTopGroup   bool     `xorm:"bool" …
```
=> feat: fix bug that initialize group children as empty array instead of empty string

controllers/auth.go
Add handling for case when provider wasn't found by name (for example renamed, disabled etc).
Prevent nil pointer error and throw valid error with valid json instead of html fatal error output.
`getProvider` returns nil in case not found provider.
=> feat: don't panic when provider not found in Login() API

web/src/ManagementPage.js
The style of the account information is fixed width, causing other components to be obscured when the displayName is too long.
Before:
After:
=> feat: fix dynamic width of navbar UI

pp/airwallex.go
Background: Istio Envoy proxy may intercept it.
=> feat: avoid using body in GET requests for AirwallexClient payment provider

Dockerfile
297.8 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
=> feat: increase frontend build memory to 4096 in Dockerfile

web/src/basic/GridCards.js
When there is only one application on the /apps page, the card width is too narrow to display the title and other content.
Before:
After:
=> feat: fix apps page grid style

controllers/verification.go
fix: when email/sms mfa is not preferred, message will send to masked address
=> feat: fix bug that when email/sms mfa is not preferred, message will send to masked address

controllers/token.go
fix: #3711
Adding also missing validation at the end on the function for `tokenTypeHint` empty.
=> feat(introspection): return correct active status for expired or revoked tokens

object/init_data.go
Fix: https://github.com/casdoor/casdoor/issues/3718
This change modifies the initialization sequence in InitFromFile() to create 
applications before users, ensuring proper dependency resolution during system 
initialization.
=> feat: improve InitFromFile() code order to fix GetOrganizationApplicationCount always returns 0 bug

web/src/PlanEditPage.js
I noticed that currencies in the Product page and in the Plan page are not equivalent.
This PR adds the missing currencies in the Plan page.
=> feat: add missing currencies in plan edit page

email/custom_http.go, email/provider.go, object/email.go, web/src/ProviderEditPage.js
Improve: https://github.com/casdoor/casdoor/issues/3684
second part pr for this issue, this time add support for specify content type and http body field mapping
=> feat: can specify content type and http body field mapping for Custom HTTP Email provider

util/system.go
fix: #3844 
maybe use MemStat.Sys instead of MemStat.Alloc can be more accurate
**Description of MemStat.Sys**
> Sys is the sum of the XSys fields below. Sys measures the virtual address space reserved by the Go runtime for the heap, stacks, and other internal data structures. It's likely that not all of the virtual address space is backed by physical memory at any given moment, though in general it all was at some point
**Description of MemStat.Alloc**
> Alloc is bytes of allocated heap objects.
=> feat: fix memory usage in sysinfo page

web/src/table/LdapTable.js
Error: When trying to visit the LDAP server page from the LDAP Table, the link was incorrect. The link has been fixed to match the edit button.
The Problem:
=> feat: fix org's LDAP table wrong link

object/ldap_conn.go
There was an issue where LDAP fields like `RegisteredAddress` and `PostalAddress` were not syncing to Casdoor.
Picture of Error (address expected):
After Fix:
Fix of: https://github.com/casdoor/casdoor/pull/3904
=> feat: fix issue that LDAP user address was not syncing

idp/douyin.go
Use nickname when available, fallback to generated username (douyinuser-xxx) when nickname is empty.
Even if a username is duplicated, the conflict is already handled in `controllers/auth.go`.
fixes #3912
=> feat: improve TikTok username generation logic

cred/argon2id.go, cred/bcrypt.go, cred/manager.go, cred/md5-user-salt.go, cred/pbkdf2-salt.go, cred/pbkdf2_django.go, cred/plain.go, cred/sha256-salt.go, cred/sha512-salt.go, object/check.go
Fix: https://github.com/casdoor/casdoor/issues/3929
=> feat: use only one salt arg in CredManager.IsPasswordCorrect()

object/resource_direct.go
I found that cloud storage (such as alicloud oss) considers the incoming fullFilePath and storage provider.PathPrefix to be concatenated as a path when uploading resources, as follows:
However, when querying (GetResources), it does not consider concatenating provider.PathPrefix, but only the incoming fullFilePath. This has led to the issue of “casibase being unable to retrieve any files when calling getresou
=> feat: fix issue that resource provider.PathPrefix is not used in GetDirectResources() API

web/src/Setting.js, web/src/auth/AuthCallback.js, web/src/auth/LoginPage.js
fix: the error effect of form post response type
Q: why change `responseType === "token"` to `responseTypes.includes("token")`? 
A: sometimes the responseType could be `token id_token`, so we need to support this.
Q: why `token` and `id_token` is same?
A: in casdoor, they are same.
demo:
- effect on fragment mode
https://github.com/user-attachments/assets/5840a860-06a8-4d13-9ed7-3cece43772fe
- effect on post_form mode
https://github.com/user-attachments/assets/c3de0fd3-6997-41e1-b7b1-b7ab12e9a8a8
=> feat: fix the error effect of form post response type

web/src/table/ProviderTable.js
fix: #3989 
- Ensure that one application contains only one Captcha provider and filter out captcha provider options when one already exists in the application
- Only affects Captcha category providers, other provider types remain unaffected
=> feat: prevent two captcha providers are added to one single application

object/permission_enforcer.go
Fix: https://github.com/casdoor/casdoor/issues/4019
if user uses custom resource type and configure the action by "POST" and try to call https://casdoor.org/docs/permission/exposed-casbin-apis#enforce with action "POST", it will fail because the database stores it as "post" not "POST"
=> feat: remove toLower conversion in getPolicies()

object/saml_idp.go
fix: use a more popular format for nameid to ensure compatibility
=> feat: use a more popular format for nameid to ensure compatibility in NewSamlResponse()

controllers/saml.go, object/saml_idp.go
As shown in this figure (Microsoft as SP for SAML login), the username parameter is not passed to the login page after redirection, resulting in the failure of the auto-fill username function. 
#4159
The purpose of this PR is to fix this issue.
=> feat: add username and loginHint to redirect URL in HandleSamlRedirect of SAML IdP

email/sendgrid.go
Sendgrid provider is failing with: 
This PR sets the Subject so it can be sent.
=> feat: fix missing subject in Sendgrid Email provider
