web/src/app.tsx
web/src/user/user-list-page.tsx

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

fix: improve user style

---

cmd/main.go
go.mod
go.sum
internal/handler/api.go
internal/handler/application/application.go
internal/handler/user.go
internal/handler/user/user.go
internal/object/application.go
internal/store/application.go
internal/store/shared/db.go
internal/store/user.go

Signed-off-by: Zixuan Liu <nodeces@gmail.com>

feat: add application module

---

README.md

Signed-off-by: Kininaru <shiftregister233@outlook.com>
Fix: https://github.com/casbin/casdoor/issues/20

added explainations to Dev and Prod usage in README

---

authz/authz.go
conf/app.conf
go.mod
go.sum
object/adapter.go

Resolved: https://github.com/casbin/casdoor/issues/45
Deployed at: https://door.chromium.link/
This demo uses postgresql.

feat: add pg for db adapter

---

README.md

For: https://github.com/casbin/casdoor/pull/50#issuecomment-829887632

feat: add info about MySQL and Postgres in readme

---

controllers/user.go
controllers/util.go
routers/router.go
web/src/PasswordModal.js
web/src/UserEditPage.js
web/src/backend/UserBackend.js
web/src/locales/en.json
web/src/locales/zh.json

Deployed at: https://door.chromium.link/
All passwords are `123`.
Change password permission logic:
`requestUser` wants to set password for `targetUser`:
``` go
hasPermission := false
if requestUser.IsGlobalAdmin {
hasPermission = true
} else if requestUserId == targetUserId {
hasPermission = true
} else if targetUser.Owner == requestUser.Owner && requestUser.IsAdmin {
hasPermission = true
}
```

feat: set password for users

---

web/src/ResetModal.js

Fixed: 
- reset phone email data error
- send code button background color error
- remoted dom api from `ResetModal.js`

Fixed reset phone email data error and removed dom API from ResetModal.js

---

idp/github.go
idp/google.go
idp/qq.go

**refactor:** 
- remove ClientId/ClientSecret/RedirectUrl in IdProvider int /idp/github.go & google.go & qq.go
- alter Scopes in QqIdProvider.Config: profile&email -> get_user_info

refactor: remove ClientId/ClientSecret/RedirectUrl in IdProvider

---

idp/provider.go
idp/weChat.go

Fix: https://github.com/casbin/casdoor/issues/28
docs: https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Authorized_Interface_Calling_UnionID.html

feat: add WeChatIdProvider

---

authz/authz.go
conf/app.conf
controllers/account.go
controllers/verification.go
object/provider.go
object/sms.go
object/verification.go
web/src/ProviderEditPage.js
web/src/ResetModal.js
web/src/UserEditPage.js
web/src/auth/SignupPage.js
web/src/backend/UserBackend.js
web/src/locales/en.json
web/src/locales/zh.json

Deployed at: https://door.chromium.link
Click to try sign up: https://door.chromium.link/signup

feat: check email and phone number when signing up

---

web/src/ResetModal.js
web/src/auth/SignupPage.js
web/src/reusable/CountDownInput.js

Deployed at: https://door.chromium.link

feat: intergrate verification code countdown as a component

---

idp/facebook.go
idp/provider.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

Fix: https://github.com/casbin/casdoor/issues/64
Deployed at: https://casdoor.leviatan.cn
Signed-off-by: WindSpirit <simon343riley@gmail.com>

feat: add facebook provider

---

controllers/auth.go

Signed-off-by: Weihao <1340908470@qq.com>

feat: login by email/phone + password

---

idp/dingtalk.go
idp/facebook.go
idp/provider.go
object/user.go
util/log.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

Fix: https://github.com/casbin/casdoor/issues/87
Signed-off-by: zKen <690898835@qq.com>

feat: add dingtalk provider

---

idp/dingtalk.go
idp/provider.go
idp/weibo.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

Fix: https://github.com/casbin/casdoor/issues/88

feat: add weibo provider

---

web/src/CropperDiv.js
web/src/PasswordModal.js
web/src/ResetModal.js

fix: unable to close the modal by clicking the inner layer

---

idp/gitee.go
idp/provider.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

feat: add gitee provider

---

object/user.go

fix: Properties can now be updated

---

web/src/App.js
web/src/OrganizationListPage.js
web/src/UserListPage.js

feat: reuse component Users

---

object/user.go

fix: The user can update the language saved in the database

---

web/src/Setting.js
web/src/auth/SignupPage.js
web/src/backend/ApplicationBackend.js

Added application default organization to avoid reporting null errors

fix: Application null error

---

object/user.go

demo:http://www.killerwing.xyz:8000/
admin/123

feat: admin can update user's organization

---

web/src/Setting.js

fix: empty email bug

---

object/init.go

fix: null properties bug

---

conf/app.conf
controllers/util.go

Deployed at: https://door.leviatan.cn
You can signup from https://forum.leviatan.cn, then try to link github account and signin with github provider, this pr will work if these are successful

fix: Move proxy address config to app.conf

---

web/package.json

fix: Fix Crowdin failing

---

idp/linkedin.go
idp/provider.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

feat: add linkedin provider

---

web/yarn.lock

Continues: https://github.com/casbin/casdoor/pull/154

fix: Update yarn.lock

---

.github/workflows/sync.yml

Fix: #158 
After this PR being merged, the translation will be restored

fix: Change commit author to casbin bot

---

web/src/component/CountDownInput.js

Fix: https://github.com/casbin/casdoor/issues/161
Signed-off-by: MRGUOKING <420919469@qq.com>
The count-down will be disabled after sending the code
Signed-off-by: MRGUOKING <420919469@qq.com>

fix: The count-down will be disabled 

---

README.md
docker-compose.yml
go-dockerfile

feat: add run casdoor through docker

---

web/src/App.js
web/src/App.less
web/src/SelectLanguageBox.js

* Removed the origin language select box on footer, and add a new one on header. #165 
* Add shadow for right dropdown when hover 
http://39.106.18.82/

feat: add language select box and background color change when hover

---

object/init.go
web/src/ProviderTable.js
web/src/RecordListPage.js
web/src/SignupTable.js
web/src/auth/PromptPage.js
web/src/auth/SignupPage.js
web/src/basic/HomePage.js

Fix: https://github.com/casbin/casdoor/issues/170

fix: db data init and frontend warning

---

web/src/UserListPage.js

demo:http://20.194.59.148:8000/
admin/123

fix: Fix the user list cannot be displayed completely

---

controllers/account.go
controllers/auth.go
controllers/base.go
controllers/user.go
controllers/util.go
controllers/verification.go
util/json.go
web/src/auth/LoginPage.js

Fix: https://github.com/casbin/casdoor/issues/109
Deployed at: https://door.chromium.link
Video: (Modified database to simulate login expiration)
https://user-images.githubusercontent.com/42638489/124791965-259fc380-df7f-11eb-84f7-8209a256ac24.mp4

feat: auto login session will expire after 24h

---

.github/workflows/sync.yml

fix: Fix PR failing checks

---

web/src/App.js

Deployed at: https://door.leviatan.cn/

fix: header selected

---

web/src/App.js
web/src/App.less
web/src/ApplicationEditPage.js
web/src/ApplicationListPage.js
web/src/LdapTable.js
web/src/OrganizationEditPage.js
web/src/OrganizationListPage.js
web/src/ProviderEditPage.js
web/src/ProviderListPage.js
web/src/RecordListPage.js
web/src/SelectLanguageBox.js
web/src/TokenEditPage.js
web/src/TokenListPage.js
web/src/UserEditPage.js
web/src/UserListPage.js
web/src/basic/HomePage.js

* Fix header overflow 
* Fix account dropdown disappear 
* Add background color and card to warp content
* Add scroll for tables
* Optimize tables for touchscreen, the table won't overflow anymore
* Improve the dropdown UI when hover
http://39.106.18.82/

feat: fix header bugs, improve UI, optimize touchscreen experience

---

web/src/ApplicationEditPage.js
web/src/ProviderTable.js
web/src/SignupTable.js

* improve preview
* improve touchscreen UI
http://39.106.18.82/

feat: improve ApplicationEditPage

---

web/src/ApplicationEditPage.js
web/src/OrganizationEditPage.js
web/src/ProviderEditPage.js
web/src/TokenEditPage.js
web/src/UserEditPage.js
web/src/auth/LoginPage.js

feat: improve border

---

web/src/App.js
web/src/LdapEditPage.js
web/src/ProviderEditPage.js
web/src/RecordListPage.js
web/src/UserEditPage.js
web/src/UserListPage.js
web/src/auth/DingTalkLoginButton.js
web/src/auth/FacebookLoginButton.js
web/src/auth/ForgetPage.js
web/src/auth/GitHubLoginButton.js
web/src/auth/GiteeLoginButton.js
web/src/auth/GoogleLoginButton.js
web/src/auth/WechatLoginButton.js
web/src/auth/WeiboLoginButton.js
web/src/component/CountDownInput.js

fix: clear all console warnings

---

web/src/OrganizationEditPage.js
web/src/ProviderEditPage.js
web/src/TokenEditPage.js
web/src/UserEditPage.js
web/src/common/AffiliationSelect.js
web/src/common/OAuthWidget.js

* improve EditPages for touchscreen
* fix: #193 
http://39.106.18.82/

feat: improve EditPages for touchscreen

---

go.mod
idp/provider.go
idp/wecom.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

feat: add wecom provider

---

web/src/auth/LinkedInLoginButton.js
web/src/auth/LoginPage.js
web/src/auth/WeComLoginButton.js

fix: add missing provider buttons

---

docker-compose.yml

feat: mount app.conf to container

---

conf/app.conf
controllers/auth.go

Part of: https://github.com/casbin/casnode/pull/342
In some conditions, Casnode users are added in Casdoor.

feat: add user initScore in app.conf

---

web/src/App.js
web/src/locales/en/data.json

fix: add 404 page

---

web/src/basic/HomePage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

Fix: https://github.com/casdoor/casdoor-website/issues/50
Signed-off-by: ffyuanda <46557895+ffyuanda@users.noreply.github.com>

fix: typo in Applications tab

---

.gitignore
main.go
storage/localsystem.go
storage/storage.go
util/filesystem/filesystem.go
util/path.go

feat: support local storage

---

web/src/AccountTable.js
web/src/OrganizationEditPage.js
web/src/OrganizationListPage.js
web/src/UserEditPage.js

Deployed at: https://door.leviatan.cn

fix: support realtime preview to organization account items

---

README.md

docs: Add i18n notice in README

---

controllers/util.go
idp/provider.go

fix: improve goland experience

---

controllers/account.go
controllers/application.go
object/storage.go
web/src/ApplicationEditPage.js
web/src/CropperDiv.js
web/src/auth/SignupPage.js
web/src/backend/ApplicationBackend.js
web/src/backend/UserBackend.js
web/src/locales/en/data.json

Fix: https://github.com/casbin/casdoor/issues/219
https://door.leviatan.cn/signup/app_forum

feat: support storage provider to terms of use file

---

web/src/AccountTable.js
web/src/App.js
web/src/ApplicationEditPage.js
web/src/ProviderTable.js
web/src/SelectRegionBox.js
web/src/SignupTable.js

1. fix #210 
2. Support case insensitivity search for SelectRegionBox
Deployed at: https://door.leviatan.cn/

fix:  table errors in frontend

---

.dockerignore
.github/semantic.yml
.github/workflows/build.yml
.github/workflows/release.yml
.releaserc.json
Dockerfile
README.md
docker-compose.yml

feat: support semantic release

---

.github/workflows/release.yml
.releaserc.json

fix: support master branch trigger

---

README.md

docs: add docker and build badges

---

object/record.go

fix: remove useless logs

---

controllers/user.go
web/src/UserEditPage.js
web/src/auth/PromptPage.js

Demo: https://door.leviatan.cn

fix: public user info page is empty

---

go.mod
go.sum
object/sms.go
web/src/ProviderEditPage.js
web/src/locales/en/data.json

`Client Id         -> Access Key            `
`Client Secret -> Secret Access Key`
`App Id            -> Account Name       `

feat: add VolcEngine as a SMS provider

---

web/src/UserEditPage.js

Demo link: https://door.leviatan.cn/users/org_forum/admin_forum

fix: accountItem load order in userEditPage

---

idp/lark.go
idp/provider.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/LarkLoginButton.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js

feat: add lark provider

---

web/src/ProviderTable.js
web/src/SelectRegionBox.js

fix: improve seletRegionBox

---

.github/workflows/sync.yml

fix: remove forked repo workflow

---

README.md

Relate to this issue: [#240](https://github.com/casbin/casdoor/issues/240)
Signed-off-by: ffyuanda <46557895+ffyuanda@users.noreply.github.com>

docs: updated README.md for npm RAM caution

---

idp/gitlab.go
idp/provider.go
object/user.go
web/src/ProviderEditPage.js
web/src/auth/GitlabLoginButton.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js

feat: add gitlab provider

---

.github/workflows/build.yml
object/provider.go
web/src/ProviderEditPage.js
web/src/ProviderListPage.js
web/src/auth/Provider.js
web/src/locales/en/data.json

feat: support web-auth way for wecom

---

Dockerfile

fix: go proxy of dockerfile

---

controllers/service.go
controllers/verification.go
object/check.go
object/email.go
object/organization.go
object/resource.go
object/sms.go
object/token.go
object/user.go
object/verification.go

fix: improvde code logic

---

web/src/App.js
web/src/Setting.js

fix: swagger bug in dev mode

---

swagger/swagger.json

resolve swagger path dump issue

fix: swagger path dump

---

controllers/service.go
controllers/verification.go
object/verification.go

Fix: https://github.com/casbin/casdoor/issues/309

fix: some bugs about SMS API

---

controllers/application.go
controllers/organization.go
controllers/provider.go
controllers/record.go
controllers/resource.go
controllers/token.go
controllers/user.go
object/application.go
object/organization.go
object/provider.go
object/record.go
object/resource.go
object/token.go
object/user.go
web/src/ApplicationListPage.js
web/src/OrganizationListPage.js
web/src/ProviderListPage.js
web/src/RecordListPage.js
web/src/ResourceListPage.js
web/src/TokenListPage.js
web/src/UserListPage.js
web/src/backend/ApplicationBackend.js
web/src/backend/OrganizationBackend.js
web/src/backend/ProviderBackend.js
web/src/backend/RecordBackend.js
web/src/backend/ResourceBackend.js
web/src/backend/TokenBackend.js
web/src/backend/UserBackend.js

Fix: https://github.com/casbin/casdoor/issues/268
ref: https://pkg.go.dev/github.com/astaxie/beego@v1.12.3/utils/pagination
Signed-off-by: “seriouszyx” <seriouszyx@foxmail.com>

feat: add server-side pagination for Tokens and Records pages

---

object/oidc_discovery.go

Fix: https://github.com/casbin/casdoor/issues/314

fix: Wrong token endpoint value #314

---

object/record.go
util/path.go

also filter "accessToken" in query.
Signed-off-by: Lex Lim <hyperzlink@outlook.com>

fix: panic while insert record when request uri too long

---

controllers/account.go
controllers/application.go
controllers/auth.go
controllers/base.go
controllers/ldap.go
controllers/link.go
controllers/oidc_discovery.go
controllers/organization.go
controllers/provider.go
controllers/record.go
controllers/resource.go
controllers/service.go
controllers/token.go
controllers/user.go
controllers/verification.go
controllers/webhook.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

Fix: https://github.com/casbin/casdoor/issues/313
feat: update swagger api json with tags

feat: update swagger api json with tags

---

conf/app.conf
controllers/auth.go
web/src/auth/AuthBackend.js
web/src/auth/LoginPage.js
web/src/auth/SamlCallback.js

feat: support third-party application to login with SAML rather than only Casdoor itself

---

.gitignore
object/check.go
object/ldap.go

feat: support checking password  through ldap server
Fix: https://github.com/casbin/casdoor/issues/290

feat: support checking password  through ldap server

---

controllers/auth.go
object/saml.go
web/src/ProviderEditPage.js
web/src/Setting.js
web/src/UserEditPage.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js
web/src/common/SamlWidget.js

feat: add Keycloak idp support

---

controllers/ldap.go
main.go
object/ldap.go
object/ldap_autosync.go
web/src/LdapEditPage.js

Fix: https://github.com/casbin/casdoor/issues/369
feat: 
backend: implement automatic synchronization for ldap users
frontend: allow setup  ldap automatic synchronization duration
Signed-off-by: Товарищ программист <2962928213@qq.com>

feat: implement automatic synchronization for ldap users

---

controllers/token.go
object/application.go
object/token.go
object/token_jwt.go
routers/auto_signin_filter.go
web/src/ApplicationEditPage.js

Fix: https://github.com/casbin/casdoor/issues/288
Fix: https://github.com/casbin/casdoor/issues/316
After researching, I draw up a flow chart for the refresh token mechanism of Casdoor as below. I have implemented the server-side and I will try the client-side. But before that, is there anything wrong with it? Welcome to discuss.

feat: add refresh token mechanism for server side

---

.github/workflows/build.yml

fix: modify image push policy
Fix: https://github.com/casbin/casdoor/issues/360

fix: modify image push policy

---

README.md

feat: add more instructions in readme

feat: add more instructions in readme

---

.github/workflows/build.yml

feat(actually fix) : set to push image with tag latest as well
This PR needs to be titled "feat" because we need to trigger a image push

feat: set to push image with tag latest as well

---

.github/workflows/build.yml
Dockerfile

feat: add all-in-one version image

feat: add all-in-one version image

---

.github/workflows/build.yml

feat: fix github-ci and republish images (actually fix)

feat: fix github-ci and republish images

---

Dockerfile

feat: add default password for mysql

feat: add default password for mysql

---

web/src/component/CountDownInput.js
web/src/locales/en/data.json
web/src/locales/zh/data.json

fix: Add loading and countdown status to the verification code sending button

---

README.md

docs: add docs for all-in-one image

docs: add docs for all-in-one image

---

object/token.go

1. refresh token does not return in /login/oauth/access_token
2. fix not checking user IsForbidden

fix: refresh token does not return

---

controllers/account.go

Fix https://github.com/casdoor/casdoor/issues/352

feat: support spring security oauth2

---

authz/authz.go
object/token.go
routers/router.go

1. add refresh_token to router and authz
2. according to [oidc doc](https://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken), adjust refresh_token endpoint return value
3. fix some refresh token bug

fix: refresh_token endpoint does not work

---

conf/app.conf
object/adapter.go

fix: Add the configuration of whether to print SQL. The default value is false

fix: Add the configuration of whether to print SQL. The default value is false

---

controllers/auth.go
controllers/token.go
object/token.go
web/src/auth/AuthBackend.js
web/src/auth/Util.js

Fix: https://github.com/casdoor/casdoor/issues/431
See [RF7636](https://datatracker.ietf.org/doc/html/rfc7636) for more details, and `code_challenge_method` just only allows "S256".

feat: add PKCE support

---

Dockerfile
docker-compose.yml

feat: remove wait-for-it
FIX #433

feat: remove wait-for-it

---

idp/baidu.go
idp/provider.go
object/user.go
web/src/Setting.js
web/src/auth/BaiduLoginButton.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js

Fix: https://github.com/casdoor/casdoor/issues/437
Although the successful access to Baidu, but due to some problems with Baidu's OAuth api, resulting in the following points need to be noted:
1. After adding the redirect url you need to reset the Client secret, or set the redirect url right after creating the application.
2. The username returned by the user information api is masked, like C*****r.
3. The api return value is inconsistent with the document.

feat: add baidu support as idp

---

idp/baidu.go

fix: baidu's display name error

---

k8s.yaml

fix: add k8s deployments example
Fix: https://github.com/casdoor/casdoor/issues/424

fix: add k8s deployments example

---

object/token.go

Fix: https://github.com/casdoor/casdoor/issues/451
The policy of code is modified as follows: 
1. code can only be used once 
2. if code is reused, the token generated with this code will be deleted. 
3. The code is valid for five minutes.

fix: add protection against attacks 

---

controllers/auth.go
controllers/token.go
web/src/auth/Util.js

fix: oauth params null value error

---

web/src/App.js

The bug:
https://user-images.githubusercontent.com/5332773/152458374-7725f8b4-9e2e-45d0-bb26-d9ec90a5f361.mp4
I can't found this file  for configuration backend server

Fix: menu redirect to swagger

---

web/src/auth/Provider.js

fix: missing state parameter

---

routers/auto_signin_filter.go

fix: IsTokenExpired function adjustment

---

util/setting_test.go

This "GetUploadXlsx" function might return an invalid value depending on the parameter.

test: add tests in setting file

---

web/src/auth/ForgetPage.js

fix: fix missing username in forgetpage
FIX #483

fix: fix missing username in forgetpage

---

controllers/auth.go
idp/goth.go
idp/provider.go
object/user.go
web/src/Setting.js
web/src/auth/AuthCallback.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js
web/src/auth/SteamLoginButton.js

fix: https://github.com/casdoor/casdoor/issues/413

feat: add steam support

---

authz/authz.go
controllers/oidc_discovery.go
object/oidc_discovery.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

fix: oidc jwks endpoint only return default cert

---

web/src/ApplicationEditPage.js
web/src/ApplicationListPage.js
web/src/CertEditPage.js
web/src/CertListPage.js
web/src/OrganizationEditPage.js
web/src/OrganizationListPage.js
web/src/PaymentEditPage.js
web/src/PaymentListPage.js
web/src/PermissionEditPage.js
web/src/PermissionListPage.js
web/src/ProviderEditPage.js
web/src/ProviderListPage.js
web/src/RoleEditPage.js
web/src/RoleListPage.js
web/src/SyncerEditPage.js
web/src/SyncerListPage.js
web/src/TokenEditPage.js
web/src/TokenListPage.js
web/src/UserEditPage.js
web/src/UserListPage.js
web/src/WebhookEditPage.js
web/src/WebhookListPage.js

Fix: https://github.com/casdoor/casdoor/issues/484
demo link: http://82.156.216.21:8000/

feat: add cancel buttons on the edit page

---

web/src/account/AccountPage.js

fix: this.props.location undefined

---

controllers/account.go
routers/record.go

Fix: https://github.com/casdoor/casdoor/issues/517

fix: Missing extendedUser in signup webhook

---

object/token.go

Fix: https://github.com/casdoor/casdoor/issues/524
When using PKCE, you can choose not to pass a secret, but if you do pass a secret, you must require it to be correct.

fix: Make secret optional when using PKCE

---

controllers/auth.go
controllers/user.go
object/application.go

Fix: https://github.com/casbin/casbin/issues/963
Fix: https://github.com/casdoor/casdoor/issues/521

fix: password leakage vulnerability caused by pagination

---

controllers/token.go
object/oidc_discovery.go
object/token.go

feat: add introspection endpoint to oidc discovery endpoint 
fix: let introspect endpoint handle formData as spec define
improve and close #425

feat: improve token introspection endpoint

---

object/token.go

fix: client_credentials' token miss some claims

---

web/package.json
web/src/index.js
web/yarn.lock

fix: add ie support (ie >= 9)

---

web/src/auth/LoginPage.js
web/src/auth/ResultPage.js
web/src/auth/SignupPage.js

fix: fix missing parameters when signup
FIX: #507

fix: fix missing parameters when signup

---

controllers/token.go
object/token.go

Fix: https://github.com/casdoor/casdoor/issues/539

fix: change client_secret in refresh_token API as optional

---

README.md

docs: add a tip to create db schema ahead of time

---

README.md

Fix: https://github.com/casdoor/casdoor/issues/546

docs: add a tip to create db for the first time

---

object/check.go

feat: support master password for ldap user

---

go.mod
go.sum
object/sms.go
web/src/ProviderEditPage.js
web/src/Setting.js
web/src/auth/Provider.js

Fix: https://github.com/casdoor/go-sms-sender/issues/6

feat: support Huawei Cloud SMS

---

web/src/App.js

fix: UI bug after switching to English

---

idp/casdoor.go
idp/provider.go
object/user.go
swagger/swagger.json
swagger/swagger.yml
web/src/ProviderEditPage.js
web/src/Setting.js
web/src/auth/CasdoorLoginButton.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js

feat: add casdoor as itself idp support

---

web/src/auth/AuthCallback.js
web/src/auth/LoginPage.js

fix: callback url param missing

---

web/src/auth/AuthCallback.js
web/src/auth/LoginPage.js

fix: oAuthParams may not exist

---

web/src/auth/AuthCallback.js
web/src/auth/LoginPage.js

fix: concatChar assignment logic

---

object/provider_item.go

Fixes: #610 
ignore the nil provider item

fix: panic when not select one provider

---

object/token.go

Fix: https://github.com/casdoor/casdoor/issues/613

feat: delete the old token when refreshing token

---

idp/github.go
idp/goth.go

fix: some idp error messages return unclear

---

object/token.go

Fix: https://github.com/casdoor/casdoor/issues/622

fix: refresh_token api return old token

---

object/check.go

LDAP user should only use the ldap connection to check the password.
Fix: https://github.com/casdoor/casdoor/issues/625

fix: adjust the password check logic for ldap user

---

object/token.go

The code is currently comparing the plain text password provided during request with the hashed password of the user.

fix: comparing hashed password with plain text password during password grant

---

object/user.go
web/src/UserEditPage.js

feat: support global admin to modify the email and phone of other users

---

idp/qq.go

fix: qq idp missing username

---

authz/authz.go
controllers/account.go
controllers/auth.go
controllers/cas.go
go.mod
go.sum
object/token_cas.go
routers/authz_filter.go
routers/router.go
routers/static_filter.go
web/craco.config.js
web/src/App.js
web/src/auth/AuthBackend.js
web/src/auth/CasLogout.js
web/src/auth/LoginPage.js
web/src/auth/Util.js

Fix: https://github.com/casdoor/casdoor/issues/604

feat: implement cas server

---

web/src/auth/ResultPage.js

Fix: https://github.com/casdoor/casdoor/issues/643

fix: sign In button in the result page has broken

---

web/src/auth/SignupPage.js

fix: link type error

---

web/src/ApplicationEditPage.js

fix: grantTypes undefined err

---

controllers/cas.go
object/saml_idp.go
object/token_cas.go
routers/authz_filter.go
routers/router.go
routers/static_filter.go

feat: implement CAS 3.0

---

Dockerfile
build.sh

Fix: https://github.com/casdoor/casdoor/issues/660

feat: implement proxy

---

controllers/token.go
controllers/types.go
controllers/user.go
idp/wechat_miniprogram.go
object/provider.go
object/token.go
object/user.go
web/src/ApplicationEditPage.js
web/src/Setting.js
web/src/auth/Provider.js

Fix: https://github.com/casdoor/casdoor/issues/400
Thanks to @mojerro 's help, I was able to develop the WeChat mini program without being familiar with it.
This PR currently only implements the most simple WeChat mini program access function, if anyone needs more specific features, please feel free to comment.
First you have to create a wechat idp in casdoor:
then login in mini program
```js
// login in mini program
// 登录
wx.login({
success: res => {
// 发送 res.code 到后台换取 openId, sessionKey, unionId
console.log(res.code)
wx.request({
url: 'http://localhost:8000/api/login/oauth/access_token',
method: "POST",
data: {
"tag":"wechat_miniprogram", //required
"client_id":"6825f4f0af45554c8952",
"client_secret": "2d0f463...",
"code": res.code,
"username": this.data.userInfo.nickName, //update …
```

feat: add wechat mini program support

---

.github/workflows/build.yml
.github/workflows/sync.yml
web/crowdin.yml

fix: cicd error

---

controllers/user.go
object/check.go
object/organization.go
web/src/OrganizationEditPage.js
web/src/OrganizationListPage.js
web/src/UserEditPage.js
web/src/locales/zh/data.json

Fix: #581 
add a organization option `enableLimitedAccess`
before enabled
after enabled

feat: add isProfilePublic setting for accessing user info

---

object/token.go

Fix: ExpiresIn of token should be seconds.

---

web/src/ProductBuyPage.js
web/src/Setting.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js

fix the display bug on the personal binding information page
Fix: https://github.com/casdoor/casdoor/issues/687

fix: fix the display bug on the personal binding information page

---

idp/casdoor.go
idp/custom.go
idp/dingtalk.go

close the http.Response body in time

fix: close the resp in time

---

controllers/account.go
controllers/auth.go
main.go
object/ldap_autosync.go
routers/record.go
util/util.go

recover when goroutine panic that will kill main program
Fix: https://github.com/casdoor/casdoor/issues/684

fix: recover when goroutine panic that will kill main program

---

authz/authz.go
controllers/token.go
routers/authz_filter.go

Fix: https://github.com/casdoor/casdoor/issues/696

fix: fix failure of introspection

---

object/ldap.go

Fix: https://github.com/casdoor/casdoor/issues/467

fix: support Microsoft AD user search #467

---

object/user_test.go
object/user_util.go

feat: DingTalk provider value case unsensitive

---

idp/okta.go
idp/provider.go
object/user.go
web/src/ProviderEditPage.js
web/src/Setting.js
web/src/auth/LoginPage.js
web/src/auth/OktaLoginButton.js
web/src/auth/Provider.js

Fix: https://github.com/casdoor/casdoor/issues/701
Add Okta as a provider for casdoor (#701 )
Showcase:
1. Create a Web app OIDC integration in Okta:
2. Add Okta as a provider in Providers page:
4. Log in using Okta:
5. User created in casdoor:

feat: add Okta provider (#701)

---

controllers/account.go
object/init.go
web/src/ApplicationListPage.js
web/src/SignupTable.js
web/src/auth/SignupPage.js

Fix: https://github.com/casdoor/casdoor/issues/722 
We can remove Email verification in signup page by configuring the application edit page.

feat: Allow to sign up with Email without verification

---

object/ldap.go

Fix: https://github.com/casdoor/casdoor/issues/715

fix: fix missing OpenLDAP uid in ldap.go

---

controllers/auth.go

close #739
Signed-off-by: xiexianbin <me@xiexianbin.cn>

fix: mistake GetApplicationLogin swagger router  (casdoor#739)

---

cred/argon2id.go
cred/manager.go
go.mod
go.sum
web/src/OrganizationEditPage.js

I created a new one because the CLA signing wouldn't work for me.

 feat: support argon2id pass manager

---

build.sh

feat: hide proxy-test output

---

web/src/ApplicationEditPage.js
web/src/backend/ApplicationBackend.js

feat: add saml metadata in application edit page

---

idp/douyin.go
idp/provider.go
object/user.go
web/src/Setting.js
web/src/auth/DouyinLoginButton.js
web/src/auth/LoginPage.js
web/src/auth/Provider.js

Add Douyin as a provider for casdoor
Fix: https://github.com/casdoor/casdoor/issues/702

feat: add Douyin OAuth provider

---

controllers/model.go
object/adapter.go
object/model.go
object/permission.go
routers/router.go
web/src/App.js
web/src/ModelEditPage.js
web/src/ModelListPage.js
web/src/PermissionEditPage.js
web/src/backend/ModelBackend.js
web/src/locales/zh/data.json

model list page
model edit page
config model in the permission edit page

feat: add model page

---

controllers/auth.go

fix: set phone prefix when disable verification code

---

controllers/saml.go

Fix: https://github.com/casdoor/casdoor/issues/767

fix: saml endpoint crash

---

controllers/auth.go

Fix: https://github.com/casdoor/casdoor/issues/762

fix: handle WeChat username conflicts

---

controllers/auth.go

fix: trigger missing webhook

---

web/src/ProductBuyPage.js
web/src/ProviderEditPage.js
web/src/ResourceListPage.js
web/src/Setting.js
web/src/SyncerEditPage.js
web/src/UserEditPage.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

fix: fix the web compiled warnings

---

web/src/auth/LoginPage.js

fix: fix incorrect cas url concatenation

feat: fix incorrect CAS url concatenation

---

web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

fix: disable jsx-a11y/anchor-is-valid

---

controllers/account.go
controllers/verification.go
object/provider.go

feat: fix stuck error when no captcha provider found

---

controllers/auth.go
controllers/oidc_discovery.go
controllers/record.go
controllers/service.go
object/storage.go
swagger/swagger.json
swagger/swagger.yml

Fix: https://github.com/casdoor/casdoor/issues/782
Added specific parameters

fix: improve swagger Api docunment

---

object/init.go

Init built-in provider: Default Captcha.

fix: init default captcha provider

---

main.go
object/application.go
routers/cors_filter.go

close: https://github.com/casdoor/casdoor/pull/813

feat: add CORS filter to fix OPTION request failure

---

captcha/hcaptcha.go
captcha/recaptcha.go
controllers/verification.go
web/src/common/CaptchaPreview.js

https://user-images.githubusercontent.com/34178764/175206529-8200c60c-4a11-49bf-93eb-9307bd50e7ad.mov

fix: captcha preview panic when clientId or clientSecret is empty

---

captcha/aliyun.go
controllers/account.go
util/crypto.go
web/src/ProviderEditPage.js
web/src/Setting.js
web/src/common/CaptchaPreview.js
web/src/common/CaptchaWidget.js
web/src/common/CountDownInput.js

https://user-images.githubusercontent.com/34178764/176194718-0256e1c4-cb83-49fa-bc53-a62170058de9.mov

feat: add aliyun captcha

---

routers/cors_filter.go

fix: fix cors filter

---

web/src/App.js

Fix: https://github.com/casdoor/casdoor/issues/673

feat: add footer to door pages

---

controllers/verification.go
web/src/ResetModal.js
web/src/Setting.js
web/src/UserEditPage.js
web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js
web/src/backend/UserBackend.js

Fix: https://github.com/casdoor/casdoor/issues/859

feat: fix bug of using email provider from wrong application

---

conf/app.conf
conf/conf_test.go
main.go
object/adapter.go

To avoid cases like https://github.com/casdoor/casdoor/issues/870

fix: set SessionOn always true

---

controllers/user.go
object/user.go

see: https://github.com/casdoor/casdoor-go-sdk/issues/25

feat: query user by `userId`

---

object/user.go

Fix: https://github.com/casdoor/casdoor/issues/882

fix: Typo in user model xorm tag

---

object/syncer_user.go
object/syncer_util.go
util/string.go

Fix: https://github.com/casdoor/casdoor/issues/880

feat: failed to sync keycloak users in the PostgreSQL database

---

web/src/PermissionEditPage.js
web/src/PermissionListPage.js

fix: actions initialized to null and model/resources not updated with the owner

---

idp/bilibili.go

Fix: https://github.com/casdoor/casdoor/issues/889

fix: typo in field tag in BilibiliUserInfo

---

web/src/BaseListPage.js
web/src/OrganizationListPage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

fix(web): fix the bug of infinity loop animate  when unauthorized

---

web/src/App.js
web/src/Setting.js
web/src/auth/SignupPage.js

Fix: https://github.com/casdoor/casdoor/issues/856

fix: invalid redirect url after sign up

---

authz/authz.go
controllers/account.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

Fix: https://github.com/casdoor/casdoor/issues/902

feat: add GET method of logout API

---

web/src/App.js
web/src/auth/LoginPage.js

[Built-in-Organization.webm](https://user-images.githubusercontent.com/33992371/180735030-83b9e957-ac88-4002-ba5d-e0d36668752b.webm)

feat: support local login for non-built-in users

---

web/src/auth/LoginPage.js
web/src/auth/Util.js

https://user-images.githubusercontent.com/34178764/181031113-549e8e51-2e2c-4b78-9eae-bfd16dace605.mov

fix: add oauth login auto close page

---

object/user_util.go

fix: fix Social Signup or Linking causes 500 Internal Server Error

---

controllers/user.go
object/init.go
object/init_data.go
object/permission.go
object/role.go
object/user.go
web/src/AccountTable.js
web/src/OrganizationListPage.js
web/src/UserEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/913

feat: get user api return roles and permissions

---

object/syncer_sync.go
object/syner_db_user.go

Fix: https://github.com/casdoor/casdoor/issues/898

fix: skip the duplicated users when sync users

---

controllers/link.go
object/provider_item.go
object/user.go
object/user_test.go
web/src/UserEditPage.js
web/src/common/OAuthWidget.js

fix: Admins should not be allowed to add third-party login for their members

---

controllers/user.go
object/check.go

unable to get the user by email or phone if the profile is not public.

fix: unable to get user if profile is private

---

controllers/user.go

Fix a bug brought by: https://github.com/casdoor/casdoor/pull/929

fix: panic triggered when user is nil

---

web/src/auth/PromptPage.js

feat: fix binding after registration causes the page to crash

---

captcha/geetest.go
captcha/provider.go
util/crypto.go
web/src/Setting.js
web/src/common/CaptchaWidget.js

Fix: #914 
https://user-images.githubusercontent.com/34178764/182762321-2b1001e2-7292-49f9-97e6-41e5b8d424ac.mov

feat: add geetest captcha

---

web/src/auth/LoginPage.js
web/src/backend/UserWebauthnBackend.js

fix: fix webauthn entry cannot add bug

---

web/src/auth/LoginPage.js
web/src/auth/ProviderButton.js
web/src/auth/SignupPage.js

Fix: [#784](https://github.com/casdoor/casdoor/issues/784)
Add provider bottons to signup page.

fix: show social buttons on signup page

---

web/src/App.js

Fix: https://github.com/casdoor/casdoor/issues/946
https://user-images.githubusercontent.com/34068205/183283533-bd0f57e5-bd76-4ee2-ad21-da92d0d750b4.mov

fix: fixed footer css

---

web/.env

Revert: https://github.com/casdoor/casdoor/pull/943 @zzjin 
Bug (white screen):

feat: delete .env to fix static file path bug

---

web/src/App.js

https://user-images.githubusercontent.com/34068205/183896971-9c189bc9-d9fc-4ffc-84f9-a571ad0991ac.mp4

feat: responsive footer

---

.github/workflows/build.yml

chore(ci): use cache to accelerate ci

---

.github/workflows/build.yml
.golangci.yml
conf/conf_test.go
controllers/token.go

chore(ci): add linter the check go code style

---

object/permission.go
object/permission_enforcer.go
object/role.go
web/src/PermissionEditPage.js
web/src/PermissionListPage.js
web/src/RoleEditPage.js
web/src/RoleListPage.js

Fix: https://github.com/casdoor/casdoor/issues/981
Confused about implementing domains, but feel free to test the RBAC model. 

feat: support RBAC model in permission

---

object/check.go

Fix: https://github.com/casdoor/casdoor/issues/1016

fix: error login logic of mobile phone login 

---

object/check.go
object/check_util.go
object/user.go

feat(login): add login limit

---

web/src/auth/LoginPage.js

fix: third-party user may login to the built-in organization

---

object/permission.go
object/permission_enforcer.go
object/role.go
web/src/PermissionEditPage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

For: https://github.com/casdoor/casdoor/issues/981

feat: support RBAC with domains model and add adapter to specify the table name for policy storage

---

object/init.go
object/permission.go

Fix: https://github.com/casdoor/casdoor/issues/1031

feat: failed to initialize the permission

---

object/check.go

fix: keep phone/email unique.

---

controllers/account.go
controllers/application.go
controllers/auth.go
controllers/base.go
controllers/cert.go
controllers/enforcer.go
controllers/ldap.go
controllers/link.go
controllers/model.go
controllers/organization.go
controllers/payment.go
controllers/permission.go
controllers/product.go
controllers/provider.go
controllers/record.go
controllers/resource.go
controllers/role.go
controllers/syncer.go
controllers/token.go
controllers/user.go
controllers/user_upload.go
controllers/util.go
controllers/webhook.go

feat: replace panic with details json error payload.

---

web/src/Setting.js
web/src/SignupTable.js
web/src/auth/PromptPage.js

Fix: #1014 
https://user-images.githubusercontent.com/34178764/184784260-e61296fb-ebfd-4d5a-ad76-bdf0e50f2721.mov

fix: add country/region selectbox in prompt page

---

web/src/Setting.js

https://user-images.githubusercontent.com/34178764/185784710-30ba94a3-7f8d-42e9-8c54-247346739ba4.mov

fix: country/region prompted page not show when signin

---

.github/workflows/build.yml

feat: fix CI bug: "/go/src/casdoor/.git/refs/heads" not found

---

web/src/auth/LoginPage.js
web/src/basic/SingleCard.js

fix: #1019
[Here](https://github.com/casbin/casnode/pull/538)'s a video to see the effect.

feat: click on the app card to log in automatically

---

.github/workflows/build.yml
Dockerfile

Revert part of: https://github.com/casdoor/casdoor/pull/1044 and all of https://github.com/casdoor/casdoor/pull/1050

feat: rollback to fix ci

---

web/src/auth/LoginPage.js

Fix: https://github.com/casdoor/casdoor/issues/1053
Fix: https://github.com/casdoor/casdoor/issues/1054

feat: fix the application edit page bug due to this.props.location.search

---

object/verification.go

Fix: #1046 
https://user-images.githubusercontent.com/34178764/185947475-de396754-173a-4979-acaf-1e8e389afc2d.mov

fix: don't start countdown if SMS fails to send

---

object/init.go
object/model.go

Fix: https://github.com/casdoor/casdoor/issues/1028

feat: check model grammar when saving and provide a ACL model as init data

---

build.sh

Fix: https://github.com/casdoor/casdoor/issues/1088

feat: buildx failed with: EROR: failed to solve: executor failed running [/bin/sh -c ./build.sh]: exit code: 127

---

object/init.go
object/permission.go

feat: migrate permission data

---

object/email.go

Fix: https://github.com/casdoor/casdoor/issues/1094

feat: add support for mysubmail

---

authz/authz.go
conf/app.conf
conf/conf.go

Fix: https://github.com/casdoor/casdoor/issues/1041

feat: add demo mode

---

build.sh

feat: fix GOPROXY bug by exporting environment variable

---

web/src/ModelListPage.js

fix: correct edit URL in model list

---

idp/dingtalk.go
idp/provider.go
object/user_util.go

feat: add dingtalk union_id

---

object/application.go
object/init.go
web/src/App.less
web/src/ApplicationEditPage.js
web/src/Setting.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

resolve: https://github.com/casdoor/casdoor/issues/941
1. This is a simple implementation that supports three positions: left, center and right. I think it's simple and enough for now, and easy for the user to setting.
https://user-images.githubusercontent.com/71440988/188483170-38eaf75a-fdf6-49f2-88ac-61f67e1054e0.mp4
3. Can select enable login form border and custom css.
https://user-images.githubusercontent.com/71440988/188815784-f4c24a83-c71e-4caf-9ad6-df7fa3d4c8eb.mp4
Signed-off-by: magicwind <2814461814@qq.com>

feat: custom login form and background

---

authz/authz.go
controllers/organization.go
object/organization.go
routers/router.go
web/src/App.js
web/src/OrganizationEditPage.js
web/src/OrganizationListPage.js
web/src/auth/LoginPage.js
web/src/backend/OrganizationBackend.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

feat: add defaultApplication for Orgnization

---

web/src/ApplicationEditPage.js
web/src/ApplicationListPage.js
web/src/Setting.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

1. Switch password to webauth mod, the form height don't change
2. Fix the githubcorner.
3. Render CSS based on whether it is in iframe or not.
https://user-images.githubusercontent.com/71440988/189536963-22c072cd-9c2a-4b92-8cb0-fca3aa8f8a3b.mp4
Signed-off-by: magicwind <2814461814@qq.com>

feat: improve login page style

---

object/organization.go

fix: missing providers and org in GetDefaultApplication

---

controllers/casbin_adapter.go
object/adapter.go
object/casbin_adapter.go
routers/router.go
web/src/AdapterEditPage.js
web/src/AdapterListPage.js
web/src/App.js
web/src/backend/AdapterBackend.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

For: https://github.com/casdoor/casdoor/issues/849
demo video:
https://user-images.githubusercontent.com/33992371/188448386-9b16d59b-2824-4258-8c6c-56be8750b12d.mp4

feat: use Casdoor to manage Casbin DB table 

---

.github/workflows/build.yml

Same goal with: https://github.com/casdoor/casdoor/pull/938

feat: add arm docker support

---

.github/workflows/build.yml

fix https://github.com/casdoor/casdoor/issues/1138

feat: fix build.yml

---

web/src/UserEditPage.js

Resolve: #1117
https://user-images.githubusercontent.com/71440988/191575212-6e1ad031-f15b-4834-8db1-2f577e581625.mp4
Signed-off-by: magicwind <2814461814@qq.com>

fix: add returnUrl for user edit page

---

web/src/App.js

feat: fix google login flash bug

---

conf/app.conf
controllers/ldapserver.go
go.mod
go.sum
main.go
object/ldapserver.go

Fix: https://github.com/casdoor/casdoor/issues/1125
demo video here
https://user-images.githubusercontent.com/101162387/191773143-b4337d4b-122e-4b32-b282-c7b62ac1942c.mp4
I have implemented the basic ldap server (support bind and search functions)

feat: support simple LDAP server

---

object/token_jwt.go

feat: revert "feat: fix openid address format"

---

go.mod
go.sum
web/src/ProviderEditPage.js
web/src/Setting.js

Fix: https://github.com/casdoor/casdoor/issues/1146

feat: add twilio SMS

---

web/src/auth/LoginPage.js

fix: fix webauthn redirection

---

web/src/auth/LoginPage.js
web/src/auth/ProviderButton.js
web/src/auth/SamlCallback.js
web/src/auth/SignupPage.js

Fix: https://github.com/casdoor/casdoor/issues/1162
add saml provider
https://user-images.githubusercontent.com/33992371/192776507-8295a5cd-b39f-4f69-a863-a5784b4a33d5.mp4
third-party
https://user-images.githubusercontent.com/33992371/192775112-dc1becc0-ab2d-4ae8-9e06-91c6e90b6971.mp4
local
https://user-images.githubusercontent.com/33992371/192775155-58ecf2d4-0943-4358-8d8c-8c7170204fd5.mp4

feat: add saml provider error

---

object/storage.go

fix: fix the delete file vulnerability issue

---

controllers/webauthn.go
web/src/auth/AuthBackend.js
web/src/auth/LoginPage.js

fix: bugs in webauthn
FIX #1143

feat: fix bugs in webauthn

---

web/src/App.js
web/src/App.less
web/src/SelectLanguageBox.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

feat: show language widget in signup and signin pages

---

web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

fix: language widget poisition without border css

---

controllers/account.go
controllers/auth.go
controllers/user.go
object/check.go
object/ldap.go
object/token.go

fix: Add restriction to username when signing up

---

web/src/UserEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/1208

fix: center loading in account page

---

object/check.go

fix: Add support for including underscores for username

---

web/src/App.js
web/src/Setting.js
web/src/auth/LoginPage.js
web/src/i18n.js

Fix: https://github.com/casdoor/casdoor/issues/1181
[![login](https://us1.myximage.com/2022/10/12/24591c0c83ba4233efaf5ee46d169357.gif)](https://img.so/image/vPpljV)

fix: translation without reloading

---

controllers/account.go
controllers/auth.go
object/check.go

Fix: https://github.com/casdoor/casdoor/issues/1223
Partially: https://github.com/casdoor/casdoor/issues/1222

feat: skip username restriction for new users coming from OAuth providers

---

.gitignore

fix: delete this accidentally added files

---

Dockerfile

Pros and Cons of non-root image
https://docs.bitnami.com/tutorials/work-with-non-root-containers/

feat: non root user for casdoor image

---

.github/workflows/build.yml
Dockerfile

successful example: 
https://hub.docker.com/r/abingcbc/casdoor
https://github.com/Abingcbc/casdoor/actions/runs/3298726507

feat: add arm docker

---

controllers/util.go

feat: fix bug in GetAcceptLanguage()

---

web/src/basic/SingleCard.js

Fix: https://github.com/casdoor/casdoor/issues/1213

fix: make the app list in homepage have the same height

---

web/src/UserListPage.js

close: #1233
https://user-images.githubusercontent.com/71440988/198178491-000a9fef-72d0-4fb4-b530-be12ace42734.mp4

fix: fix duplicated user bug in user list page

---

web/src/Setting.js
web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/PromptPage.js
web/src/auth/ResultPage.js
web/src/auth/SignupPage.js

Fix: #1227 
substitute goToLogin with frontend router

fix: login / signin frontend router

---

object/application.go
object/cert.go
object/model.go
object/organization.go
object/provider.go
object/role.go
object/user.go

Fix: https://github.com/casdoor/casdoor/issues/1207
demo video here
https://user-images.githubusercontent.com/101162387/199184930-1d0e94b3-ed1b-4d37-89ab-ef910a95a1b5.mp4

feat: change all occurrences when a object name is changed

---

controllers/provider.go
object/provider.go
routers/router.go
web/src/AdapterListPage.js
web/src/App.js
web/src/ApplicationEditPage.js
web/src/BaseListPage.js
web/src/ModelListPage.js
web/src/PaymentListPage.js
web/src/PermissionListPage.js
web/src/ProviderEditPage.js
web/src/ProviderListPage.js
web/src/RoleListPage.js
web/src/SyncerListPage.js
web/src/WebhookListPage.js
web/src/backend/ProviderBackend.js

close: https://github.com/casdoor/casdoor/issues/1217
The built-in users and global admin and manager all providers. The organization admin can manager their own providers.
Wait for review.
https://user-images.githubusercontent.com/71440988/199399578-5380b3e7-109d-497f-b1ec-beac9805eb73.mp4

feat: support add providers inside the Organization scope

---

web/src/SystemInfo.js

fix: system info mobile view

---

web/src/auth/ForgetPage.js

fix: forget page mobile view

---

object/syncer_user.go

feat: fix memory leak problem

---

web/src/App.less
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

feat: fix select language box overlay

---

object/verification.go

Fix: https://github.com/casdoor/casdoor/issues/1291

feat: fix verification code send time's limit logic

---

controllers/enforcer.go
object/permission_enforcer.go

See #1305 for more detail. 
Fix: https://github.com/casdoor/casdoor/issues/1305

feat: add parameter v0 for Casbin APIs

---

object/webhook.go
web/src/WebhookEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/1304

feat: add webhook for add/update org/provider

---

controllers/auth.go
controllers/resource.go
controllers/service.go
controllers/util.go
deployment/deploy_test.go
object/init.go
object/init_data.go
object/token.go
util/string.go
util/string_test.go
web/src/CropperDiv.js
web/src/UserEditPage.js

feat: fix the bug that admin cannot upload avatar for other users

---

controllers/casbin_adapter.go
object/casbin_adapter.go
routers/router.go
util/struct.go
web/src/AdapterEditPage.js
web/src/AdapterListPage.js
web/src/Setting.js
web/src/backend/AdapterBackend.js
web/src/common/PoliciyTable.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

close: #1311 
https://user-images.githubusercontent.com/71440988/203560439-7a550bbb-aad1-402a-b30d-56dfd15cc0a5.mp4

feat: finish policy list management

---

captcha/provider.go
captcha/turnstile.go
web/src/Setting.js
web/src/common/CaptchaWidget.js

feat: add cloudflare turnstile captcha

---

controllers/permission.go
routers/router.go

Support API get-permissions-by-role

feat: add get-permissions-by-role API

---

web/src/ApplicationEditPage.js

fix: application edit mobile view

---

conf/app.conf
conf/conf.go
conf/conf_test.go
controllers/application.go
controllers/organization.go
controllers/provider.go
controllers/user.go
controllers/util.go

Fix: https://github.com/casdoor/casdoor/issues/1332

feat: add quota limitation to organizations, users, providers and applications

---

web/src/AdapterListPage.js
web/src/ApplicationEditPage.js
web/src/ApplicationListPage.js
web/src/CertListPage.js
web/src/ModelListPage.js
web/src/OrganizationEditPage.js
web/src/OrganizationListPage.js
web/src/PaymentListPage.js
web/src/PermissionListPage.js
web/src/ProductListPage.js
web/src/ProviderEditPage.js
web/src/ProviderListPage.js
web/src/RoleListPage.js
web/src/SyncerListPage.js
web/src/TokenListPage.js
web/src/UserEditPage.js
web/src/UserListPage.js
web/src/WebhookListPage.js

For: https://github.com/casdoor/casdoor/pull/1339

fix: handle add error message in frontend

---

web/src/ProviderEditPage.js

fix: provider sort alphabetical order

---

web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

fix: disable formcss in mobile

---

web/src/App.js
web/src/App.less
web/src/Setting.js
web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

https://user-images.githubusercontent.com/71440988/205692869-04bc4856-7264-47e1-bcf8-fc0a909fca60.mp4

feat: refactor layout and fix footer CSS

---

web/src/AdapterListPage.js
web/src/ApplicationListPage.js
web/src/ResourceListPage.js

Fix some incomplete path lead to 404.

fix: fix invalid url in applications page

---

web/package.json
web/src/SelectLanguageBox.js
web/src/common/OAuthWidget.js
web/yarn.lock

1. fix the link button with disabled style but can click.
https://user-images.githubusercontent.com/71440988/206837650-589f62b0-453f-446f-95ae-bcca87477836.mp4

fix: the link button with disabled style but can click

---

controllers/verification.go
web/src/ResetModal.js
web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js
web/src/backend/UserBackend.js
web/src/common/CountDownInput.js

Fix: https://github.com/casdoor/casdoor/issues/1395
> 4. Change account info -> account for the Email/Phone should exist
In addition, when changing the phone or email for the account, we can't get the user by this new phone or email

feat: fix bug in signup and reset phone and email

---

init_data.json.template
object/init_data.go
object/token.go

feat: add all other missing objects to init_data

---

init_data.json.template

Fix https://github.com/casdoor/casdoor/issues/1410

feat: add valid key for creating token

---

controllers/auth.go
idp/provider.go
object/user.go
web/src/Setting.js
web/src/auth/LineLoginButton.js
web/src/auth/Provider.js
web/src/auth/ProviderButton.js

Fix: https://github.com/casdoor/casdoor/issues/1338

feat: add Line support as OAuth 3rd-party login

---

web/src/Setting.js

feat: fix absolute URL redirection

---

web/src/Setting.js

* open login page in the current tab 
* user can not go back to last page, like the signup / password reset page

feat: fix bug in redirectToLoginPage()

---

web/src/UserEditPage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json
web/src/propertyTable.js

close: #1375
https://user-images.githubusercontent.com/71440988/210061716-d66e3343-0db1-476b-92f0-b624c96339b3.mp4

feat: edit user properties

---

object/oidc_discovery.go

feat: add query and fragment response mode declare in OIDC

---

controllers/user.go
web/src/AccountTable.js
web/src/UserEditPage.js

feat: check permission when update user

---

controllers/account.go
object/permission.go
object/role.go

Hide sensitive information when GetAccount

fix: add GetMaskedRoles and GetMaskedPermissions when GetAccount

---

controllers/user.go

Fix: #1452
Fix bug in: https://github.com/casdoor/casdoor/pull/1438

feat: fix `checkPermissionForUpdateUser()` logic

---

controllers/auth.go
i18n/locales/de/data.json
i18n/locales/en/data.json
i18n/locales/es/data.json
i18n/locales/fr/data.json
i18n/locales/ja/data.json
i18n/locales/ko/data.json
i18n/locales/ru/data.json
i18n/locales/zh/data.json
object/check.go
object/check_util.go
object/verification.go

We have a limit when signing-in with `username` and `password` but with `code` is not yet, which may be the script burst code.

feat(login): add code login limit

---

controllers/auth.go

Response refresh token when login with token or id_token.

feat: add refresh token to token login response

---

controllers/auth.go
object/application.go
web/src/ApplicationEditPage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/zh/data.json

feat: auto link accounts with the same email

---

controllers/user_util.go

An App with basic auth cannot update user.

feat: fix the bug that "app - global" admin is not allowed to update user

---

object/model.go
object/permission.go
object/permission_enforcer.go

feat: fix compatibility issue between Casbin request and model

---

object/model.go
object/permission.go
object/permission_enforcer.go
object/role.go

Continue PR: https://github.com/casdoor/casdoor/pull/1153

feat: update permission rule when role updated

---

object/application.go

Fix: https://github.com/casdoor/casdoor/issues/1140
Check if they are existed before updating or adding the application.

fix: check the duplicated Application ClientId

---

web/src/Setting.js
web/src/SignupTable.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

feat: terms of use auto checked

---

object/token_jwt.go

Fix: https://github.com/casdoor/casdoor/issues/1170

feat: reduce the size of token's user object

---

web/src/auth/SignupPage.js

feat: fix missing phone number prefix in login screen

---

controllers/model.go
object/model.go

feat: return the correct error message in the Edit Model

---

web/src/ManagedAccountTable.js
web/src/UserEditPage.js
web/src/common/PoliciyTable.js
web/src/propertyTable.js

Table do not have unique key, it will cause wrong result when doing delete or edit and other operations.
https://user-images.githubusercontent.com/71440988/216229842-63bb9a16-3ac0-4072-9e96-46f611119213.mp4
https://user-images.githubusercontent.com/71440988/216230053-68cccc7f-11cd-4654-88e3-db70f569cd84.mp4

fix: table do not have unique key

---

controllers/ldapserver.go

fix #1508, and add user password in ldap server search result to support authentication in some ldap client like freeradius.

feat: add user password in ldap server search result

---

object/resource.go
object/storage.go

Fix: https://github.com/casdoor/casdoor/issues/1514

feat: fix the Unicode filename encoding bug in storage provider

---

object/storage.go

feat: fix the upload file name contains space problem

---

web/src/App.js

Fix: #1498 
https://user-images.githubusercontent.com/41513919/218043889-52080aeb-03dd-4e83-ac4e-784e260a2df1.mp4

feat: fix click MenuItem blank part invalid bug

---

controllers/resource.go
object/storage.go

Fix: https://github.com/casdoor/casdoor/issues/1529

feat: fix file name length problem

---

controllers/token.go
object/token.go

`To refresh an Access Token, the Client MUST authenticate to the Token Endpoint`
ref: https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens

feat: support refresh token on GetOAuthToken

---

go.mod
go.sum
object/email.go
web/src/Setting.js

Fix: https://github.com/casdoor/casdoor/issues/1516
Continue on: https://github.com/casdoor/gomail/commit/a9e9670c93b32292e668cdb2bc0b154e84c2cfbb
Choose this option to skip username check:

feat: replace gomail and disable the Email username check for Mailtrap

---

web/src/App.js
web/src/ApplicationEditPage.js
web/src/Conf.js
web/src/EntryPage.js
web/src/OrganizationEditPage.js
web/src/ResetModal.js
web/src/SelectLanguageBox.js
web/src/SelectRegionBox.js
web/src/Setting.js
web/src/UserListPage.js
web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js
web/src/backend/UserBackend.js
web/src/common/SendCodeInput.js
web/src/common/theme/ThemeEditor.js

fix: #1545
https://user-images.githubusercontent.com/71440988/218305733-966d9d71-6c45-4654-bc5d-a3e4a4a0385d.mp4

fix: region don't display in userEditPage

---

controllers/account.go

Fix: https://github.com/casdoor/casdoor/pull/1494#discussion_r1095675265

fix: session Id error

---

.github/workflows/build.yml

feat: e2e test will auto wait localhost:7001

fix: fix CI error by auto waiting for localhost:7001 to start up

---

web/src/EntryPage.js
web/src/auth/CasLogout.js

Fix: https://github.com/casdoor/casdoor/issues/1551

feat: fix CAS login crash bug

---

web/src/backend/FetchFilter.js

judging modification operator by `response msg` in demoMode

fix: detect access denied by response message for demo mode

---

controllers/verification.go

Fix: https://github.com/casdoor/casdoor/issues/1573

feat: fix captcha none type bug

---

web/package.json
web/src/App.js

Fix: #1553 
Ref: https://ant.design/docs/react/compatible-style-cn

feat: fix compatibility with lower version browsers like Chrome 87

---

object/saml_idp.go

Fix: https://github.com/casdoor/casdoor/issues/1582

feat: improve saml idp err message

---

util/validation.go
web/src/OrganizationListPage.js
web/src/Setting.js
web/src/UserEditPage.js
web/src/auth/SignupPage.js
web/src/backend/UserBackend.js
web/src/common/PhoneNumberInput.js
web/src/common/SendCodeInput.js

https://user-images.githubusercontent.com/71440988/221501985-bdd46745-0bf6-43dd-b977-c753d9f59419.mp4

feat: fix bug that signup country code is undefined

---

web/src/UserEditPage.js
web/src/auth/SignupPage.js
web/src/common/PhoneNumberInput.js

https://user-images.githubusercontent.com/71440988/221573280-3adf07ea-199f-4e9f-ae7f-f2239254d954.mp4

fix: fix bug form country code init error

---

manifests/casdoor/templates/configmap.yaml
manifests/casdoor/templates/deployment.yaml
manifests/casdoor/values.yaml

remove hardcode in `template/configmap.yaml`.

feat: support making configs in values.yaml

---

web/package.json
web/src/App.js
web/yarn.lock

anted: https://ant-design.gitee.io/docs/react/compatible-style-cn#css-%E9%80%BB%E8%BE%91%E5%B1%9E%E6%80%A7
relative issue: https://github.com/ant-design/ant-design/issues/38837

feat: fix CSS where polyfill to support Safari 13 below browsers

---

captcha/aliyun.go
controllers/verification.go
object/check.go
web/src/ProviderEditPage.js
web/src/auth/LoginPage.js
web/src/backend/UserBackend.js
web/src/common/CaptchaModal.js
web/src/common/CaptchaPreview.js
web/src/common/CaptchaWidget.js
web/src/common/SendCodeInput.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

feat: support all captcha for login

---

web/src/ProviderEditPage.js
web/src/UserEditPage.js
web/src/auth/SignupPage.js
web/src/common/CountryCodeSelect.js

fix: #1612
https://user-images.githubusercontent.com/71440988/222963216-93a08b4d-b61d-42fb-9aa6-d2bbe0e8b305.mp4

feat: fix empty value of countryCode for signup

---

object/permission.go

Fix: #1613 
Remove extra field to match current `Model`

feat: remove ID field in enforcement

---

controllers/account.go
controllers/ldap.go
web/src/App.js
web/src/LdapEditPage.js
web/src/LdapSyncPage.js
web/src/LdapTable.js
web/src/backend/LdapBackend.js

feat: fix LDAP page crash

---

web/src/App.js

View the change: https://imp2002.casdoor.com

feat: fix incompatibility css `inset` when Safari version <=14.1

---

.fleet/settings.json
idp/dingtalk.go

Fix: https://github.com/casdoor/casdoor/issues/1634

feat: Dingtalk provider supports fetching organization email

---

controllers/auth.go

feat: use GetUserCount to optimize login performance

---

controllers/ldap.go
i18n/generate_test.go
object/check.go
object/ldap.go
object/ldap_autosync.go
web/src/LdapEditPage.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fr/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ru/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

feat: support LDAP with SSL/TLS enabled

---

main.go

Fix: https://github.com/casdoor/casdoor/issues/1654

fix: disable cookie for static files

---

Dockerfile
build.sh
controllers/system_info.go
util/system.go
util/system_test.go

Fix: https://github.com/casdoor/casdoor/issues/1556

feat: support getting version info in Docker

---

main.go

feat: revert PR: "fix: disable cookie for static files"

---

object/permission_enforcer.go

getEnforcer is used in many functions relating to role and permission. Getting all policies while init enforcer causes the application to be extremely slow.

feat: optimize getEnforcer, only load filtered polices

---

.github/workflows/build.yml
Dockerfile
controllers/system_info.go
util/system.go
util/system_test.go

Fix: https://github.com/casdoor/casdoor/issues/1556

feat: support getting versionInfo in docker

---

web/src/auth/LoginPage.js

Fix: #1589 
https://user-images.githubusercontent.com/41513919/226655440-5e050e41-d2ee-4013-aa17-57ed3c7396fc.mp4

feat: support `popup` mode in OAuth

---

web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/SelfLoginButton.js
web/src/auth/SignupPage.js

feat: fix the bug that autoSignin generates two callback AJAX calls

---

object/token.go

Fix: https://github.com/casdoor/casdoor/issues/1594

feat: fix name format in application login: GetClientCredentialsToken()

---

web/src/Setting.js
web/src/auth/LoginButton.js
web/src/auth/ProviderButton.js

feat: [SAML + long button crash] fix `Disabling "Enable password" leads to white app page when SAML provider is active`

---

web/src/auth/SignupPage.js

fix: https://github.com/casdoor/casdoor/issues/1690

feat: fix phone validation bug in signup page

---

web/src/ApplicationEditPage.js
web/src/backend/ApplicationBackend.js

feat: filter not selected provider item

---

authz/authz.go
controllers/auth.go
controllers/user.go
controllers/verification.go
ldap/util.go
object/check.go
object/verification.go
routers/router.go
util/string.go
web/src/auth/ForgetPage.js
web/src/backend/UserBackend.js

fix: #1703
https://user-images.githubusercontent.com/71440988/230405158-bfe318d0-b883-49ef-a654-49c4a6703748.mp4

feat: optimize the "forget password" page

---

go.mod
go.sum

fix: rollback the version of webauthn in go mod to fix "atob" bug

---

controllers/auth.go
object/saml_sp.go

feat: handle error when parsing samlResponse

---

controllers/account.go
web/src/auth/ResultPage.js
web/src/auth/SignupPage.js
web/src/table/SignupTable.js

feat: add rule option for phone in application's signup page

---

object/user_util.go

feat: fix display name null error during 3rd-party binding

---

object/provider.go
util/string.go

Fix: #1743 
Endpoint should be no scheme.
https://user-images.githubusercontent.com/41513919/232787252-654c9368-9674-4c12-9a49-350bbb2116c4.mp4

feat: fix Tencent Cloud OSS storage connect incorrect issue

---

web/package.json
web/yarn.lock

feat: rollback antd to v5.2.3 to fix application edit page crash

---

web/src/EntryPage.js

fix: #1647 
https://user-images.githubusercontent.com/71440988/233366848-3738e60e-e960-4fe6-8b87-2cab7ba50de2.mp4

feat: fix wrong CAS login mode

---

web/src/EntryPage.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

fix: #1746
https://user-images.githubusercontent.com/71440988/233366476-33fcbd4b-78de-4f47-be1a-782370f19837.mp4

feat: fix bug that can not get application in signup/oauth/ router

---

web/src/AdapterListPage.js
web/src/ApplicationListPage.js
web/src/ChatListPage.js
web/src/MessageListPage.js
web/src/ModelListPage.js
web/src/PaymentListPage.js
web/src/PermissionListPage.js
web/src/ProviderListPage.js
web/src/RoleListPage.js
web/src/SessionListPage.js
web/src/SyncerListPage.js
web/src/TokenListPage.js
web/src/WebhookListPage.js

fix: Fixed name duplication problem

---

authz/authz.go
controllers/prometheus.go
go.mod
main.go
object/prometheus.go
routers/prometheus_filter.go
routers/router.go
web/src/SystemInfo.js
web/src/backend/SystemInfo.js
web/src/table/PrometheusInfoTable.js

Fix: https://github.com/casdoor/casdoor/issues/1774

feat: support for prometheus

---

object/permission.go
object/role.go

the query will match both ["organize/user_1"] and ["organize/user_11"]

fix: make query with like more precise

---

ai/ai.go

Is an AI response that supports streaming return

feat: AI responses support streaming

---

object/check.go
object/migrator.go
object/migrator_1_314_0_PR_1838.go
object/migrator_1_314_0_PR_1841.go
object/user.go
object/user_cred.go
object/user_util.go

feat: User should have PasswordType like Organization

---

web/src/App.js
web/src/CertEditPage.js
web/src/CertListPage.js

fix #1847
https://github.com/casdoor/casdoor/assets/34300181/ea37ea67-908f-4747-bcbd-249fefe775a1

fix: resolve the problem of cert being unable to be accessed properly

---

controllers/account.go
controllers/auth.go
controllers/ldap.go
controllers/util.go
object/ldap_autosync.go
object/ldap_conn.go
object/organization.go
web/src/LdapSyncPage.js

feat: compatible different uid of LDAP server

---

object/check.go
object/ldap_conn.go
web/src/LdapEditPage.js

fix: add sAMAccountName for AD search

---

controllers/base.go

fix: sdk user is not Global Admin

---

web/package.json
web/src/auth/MfaVerifyForm.js
web/yarn.lock

fix: #1857
https://github.com/casdoor/casdoor/assets/71440988/7b80ab8c-0032-428e-ae51-472461401796

feat: fix UI in IE11

---

web/package.json
web/src/auth/MfaVerifyForm.js
web/yarn.lock

fix: revert "feat: fix UI in IE11"

---

web/src/ResourceListPage.js

fix #1874
Demonstrated the crud of resources by global admin and org admin.
https://github.com/casdoor/casdoor/assets/34300181/86585303-71da-46ef-8032-555a32da582f

fix: resolve get resource list problem

---

object/syncer_public_api.go
object/syncer_user.go

feat: revert "feat: fix the bug that sycner does not initialize"

---

object/provider.go

feat: resolve casdoor as SAML SP with keycloak login not work bug

---

object/adapter.go

feat: resolve user pages malfunction after using tableNamePrefix

---

controllers/payment.go
controllers/product.go
object/payment.go
object/product.go
object/product_test.go
pp/alipay.go
pp/dummy.go
pp/gc.go
pp/paypal.go
pp/provider.go
pp/wechatpay.go

fix: fix bug in PayPal payment provider

---

web/src/PaymentResultPage.js

fix: clean timeout when componentWillUnmount in PaymentResult page

---

controllers/user.go
object/user.go
routers/authz_filter.go
routers/base.go
routers/router.go
web/src/OrganizationListPage.js
web/src/UserEditPage.js
web/src/backend/UserBackend.js
web/src/table/AccountTable.js

Fix: https://github.com/casdoor/casdoor/issues/1240
https://github.com/casdoor/casdoor/assets/34300181/2d27b5f7-4af9-41c8-bcdc-aa677135a3b5

feat: add access key and secret key for user

---

object/permission.go
object/permission_enforcer.go
object/role.go
object/user.go
util/string.go

The current function doesn't get all permissions and roles of an user, there are still related roles and related permissions (with sub-roles supported)

feat: get all role/permission of an user

---

storage/minio_s3.go

Reverts: casdoor/casdoor#1818
Fix: https://github.com/casdoor/casdoor/issues/1974

feat: Revert "fix: fix URL path in MinIO storage provider"

---

controllers/user.go
object/group.go
object/user.go
object/user_group.go
web/src/GroupEdit.js
web/src/GroupList.js
web/src/GroupTreePage.js
web/src/UserEditPage.js
web/src/UserListPage.js
web/src/backend/UserBackend.js

fix: Deprecate the id field in group

---

controllers/enforcer.go
object/permission_enforcer.go

The current code not return error when permission not found, which cause panic when getEnforcer with a nil permission

feat: handle error when permission not found

---

web/src/auth/LoginPage.js

Current code not support show sign in form (application enabled code sign in) when password is disable.
It should work independent of each other

feat: show code signin page with password disabled

---

controllers/organization.go

fix https://github.com/casdoor/casdoor/issues/2024

fix: getOrganization without pagination for global admin

---

controllers/auth.go
controllers/mfa.go
controllers/pricing.go
controllers/subscription.go
controllers/webauthn.go
swagger/swagger.json
swagger/swagger.yml

Fix: https://github.com/casdoor/casdoor/issues/1941

fix: fix Swagger docs page

---

controllers/resource.go
swagger/swagger.json
swagger/swagger.yml

swagger files are all auto generated.
So irrelevant edition in swagger.json/yaml should be caused by not updating swagger file in earlier commits. And it could be checked.

docs: add swagger docs for Resource-API

---

web/src/auth/LoginPage.js

Fix: https://github.com/casdoor/casdoor/issues/2047

feat: fix bug that the password input disappears in login window

---

object/provider.go

Fix: https://github.com/casdoor/casdoor/issues/2060

feat: fix the error when user uploads avatar to minio (https)

---

web/src/common/theme/ThemeEditor.js

fix: #2081
https://github.com/casdoor/casdoor/assets/71440988/1e7499d5-e7ae-4dad-90c3-b1db247688bd

feat: fix bug that themeEditor can not load saved theme data

---

object/permission_enforcer.go

Fix: https://github.com/casdoor/casdoor/issues/2102

feat: fix `Effect` in Casbin rule

---

web/src/common/modal/AgreementModal.js
web/src/index.css

Fix: https://github.com/casdoor/casdoor/issues/2097

feat: improve TermsOfUse UI in mobile

---

controllers/plan.go
controllers/product.go
web/src/ApplicationEditPage.js
web/src/ChatEditPage.js
web/src/MessageEditPage.js
web/src/PaymentResultPage.js
web/src/PlanEditPage.js
web/src/PricingEditPage.js
web/src/ProductEditPage.js
web/src/RoleEditPage.js
web/src/SubscriptionEditPage.js

Fix: https://github.com/casdoor/casdoor/pull/2111

feat: fix response data assignment error

---

object/permission.go
object/role.go
routers/authz_filter.go
web/src/PermissionEditPage.js
web/src/PermissionListPage.js
web/src/PlanListPage.js
web/src/RoleEditPage.js
web/src/RoleListPage.js

for supporting other character in permission/role name, we en/decodeURI permission/role name

feat: en/decodeURI in permission/role name

---

object/application.go
object/user.go

The current code still mask application with admin of an organization in edit application page

fix: unmask application for org admin

---

object/ldap.go

fix: https://github.com/casdoor/casdoor/issues/2135

fix: update ldap admin pwd only if changed

---

controllers/webhook.go
routers/router.go
swagger/swagger.json
swagger/swagger.yml

fix: add "authorize" button in swagger and defaultValue in API (#2112 )
Fix: https://github.com/casdoor/casdoor/issues/2112

feat: add authorize button and defaultValue

---

authz/authz.go
controllers/casbin_api.go
object/enforcer.go

fix: support enforcerId parameter in Enforce API

---

object/payment.go
pp/paypal.go
pp/provider.go
web/src/PaymentResultPage.js

https://github.com/casdoor/casdoor/issues/1908

feat: support payment cancel state

---

object/adapter.go
web/src/AdapterEditPage.js
web/src/AdapterListPage.js

Fix: https://github.com/casdoor/casdoor/issues/2171

fix: revert adapter port vartype to int

---

web/src/ProviderListPage.js

fix: fix add provider error

---

object/adapter.go
util/struct.go
web/src/table/PoliciyTable.js

feat: save policy in adapter edit page

---

object/ldap_conn.go
web/src/LdapSyncPage.js

feat: fix LDAP mobile field incorrect mapped

---

object/syncer_sync.go
object/syncer_user.go
object/syncer_util.go
util/string.go
web/src/SyncerEditPage.js

fix: synchronize update the syncers (#1933 )
Fix: https://github.com/casdoor/casdoor/issues/1933

fix: synchronize update the syncers

---

controllers/get-dashboard.go
object/get-dashboard.go
routers/router.go
web/package.json
web/src/backend/DashboardBackend.js
web/src/basic/HomePage.js
web/yarn.lock

Fix: https://github.com/casdoor/casdoor/issues/2110

feat: support dashboard in homepage

---

.github/workflows/build.yml
web/src/UserEditPage.js
web/src/common/modal/EnableMfaModal.js
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fr/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/tr/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

fix: #2215 
https://github.com/casdoor/casdoor/assets/71440988/37566cc9-12f1-4a06-b1e8-ca28a5664f4b

feat: support admin to enable MFA for other users

---

controllers/adapter.go
controllers/enforcer.go
object/adapter.go
object/enforcer.go
util/casbin.go
web/src/AdapterEditPage.js
web/src/EnforcerEditPage.js
web/src/backend/AdapterBackend.js
web/src/backend/EnforcerBackend.js
web/src/table/PolicyTable.js

fix: #2222
https://github.com/casdoor/casdoor/assets/71440988/f489188e-8902-4389-a805-450f370ea17e

feat: move policy table from adapter to enforcer and improve it

---

web/package.json
web/yarn.lock

chore: fix yarn build warning

---

web/package.json

Has make sure these packages are dev dependency.

chore: put some dev dependency package to right place

---

controllers/organization.go
object/token_cas.go
web/src/auth/LoginPage.js
web/src/backend/OrganizationBackend.js

chore: Revert "feat: restrict redirectUrls for CAS login"

---

object/syncer_util.go
web/src/table/SyncerTableColumnTable.js

Fix: https://github.com/casdoor/casdoor/issues/2239
feat: add fields to syncer (PreferredMfaType, TotpSecret, SignupApplication) #2239

feat: add fields to syncer #2239

---

controllers/account.go
object/check.go
web/src/table/SignupTable.js

Fix: https://github.com/casdoor/casdoor/issues/2256

feat: password and invitation code verification rules

---

object/syncer_sync.go

fix: change the id to key in syncer

fix: change the id to key in syncer

---

web/src/common/OpenTour.js

fix: distinguish between pages that can tour or not

fix: fix tour disabled state

---

object/ormer.go

feat: fix can not create db when using pg with a dbname in DSN

---

idp/facebook.go
web/src/auth/Web3Auth.js

https://github.com/Selflocking/linkchecker/actions/runs/6058177987

docs: fix all dead links

---

authz/authz.go
controllers/payment.go
controllers/product.go
object/payment.go
object/product.go
pp/wechatpay.go
web/package.json
web/src/App.js
web/src/EntryPage.js
web/src/ProductBuyPage.js
web/src/ProviderEditPage.js
web/src/QrCodePage.js

Fix: https://github.com/casdoor/casdoor/issues/2259

feat: support wechat pay

---

web/src/auth/SignupPage.js

Fix: https://github.com/casdoor/casdoor/issues/2301

feat: fix bug in pricing when signup by phone

---

web/src/BaseListPage.js
web/src/SystemInfo.js
web/src/basic/Dashboard.js

fix:cancel the tour function at mobile

fix: hide tour component for mobile

---

email/acs.go
email/azure_acs.go
email/provider.go
email/smtp.go
object/email.go
web/src/ProviderEditPage.js
web/src/Setting.js

Fix: casdoor/casdoor-website#562

feat: support acs email provider

---

object/user_util.go

* fix: Fixed the missing permission check when updating the score field.
* Update object/user_util.go

fix: fix update score permission check

---

controllers/account.go

Fix: https://github.com/casdoor/casdoor/issues/2336
Earlier if redirect_uri was equal to "", token was successfully invalidated, but response had an error. Fixed it

feat: make redirect_uri really optional in logout route

---

controllers/account.go
go.mod
go.sum
object/user_enforcer.go

Update casbin/casbin/v2 to 2.77.2 version

feat: update casbin to 2.77.2

---

object/provider.go

fix: empty AzureAD tenant id

---

conf/app.conf
go.mod
go.sum
main.go
radius/server.go
radius/server_test.go
radius/util.go

Only support `AccessRequest` currently
Part of: https://github.com/casdoor/casdoor/issues/2294

feat: add some Radius protocol code

---

main.go

feat: run RecordMessage() filter after API handling

---

go.mod
go.sum

Fix: https://github.com/casdoor/casdoor/issues/2386

feat: update go-sms-sender to fix Twilio template error

---

object/application.go
object/saml_idp.go
web/src/ApplicationEditPage.js
web/src/table/SamlAttributeTable.js

Fix: https://github.com/casdoor/casdoor/issues/2168

feat: support tencent cloud SAML SSO authentication with casdoor 

---

object/syncer_public_api.go

feat: respect isReadOnly in the syncer

---

object/saml_idp.go

for https://github.com/casdoor/casdoor/issues/2428
`xml-exc-c14n#` is the recommended version

feat: change canonicalizer algorithm to xml-exc-c14n#

---

object/role.go

If set tableNamePrefix in app.conf, while cause sql error

feat: fix bug that tableNamePrefix caused getRolesByUserInternal() to fail

---

go.mod
go.sum

Fix: https://github.com/casdoor/casdoor/issues/2446
Related PRs: 
1. https://github.com/casdoor/go-reddit/pull/1 
2. https://github.com/casdoor/notify/pull/8

feat: fix go-reddit module checksum mismatch

---

object/provider.go

Fix: https://github.com/casdoor/casdoor/issues/2374

fix: fix Okta provider no host issue

---

web/src/auth/PromptPage.js

Fix: https://github.com/casbin/casdoor/issues/2417
1. Fixed the incorrect prompt page preview in the application edit page.
2. Fixed the redirection error after signup -> binding; now it redirects directly to the home page after signup and binding.

feat: fix the UI and navigation errors on the prompt page

---

ldap/server.go

fix: support LDAP in linux

---

web/src/auth/Provider.js
web/src/auth/Util.js

Fix: https://github.com/casbin/casdoor/issues/2498
Fix: https://github.com/casbin/casdoor/issues/124

feat: use short state for OAuth provider

---

web/src/auth/LoginPage.js
web/src/auth/mfa/MfaAuthVerifyForm.js

Fix: https://github.com/casbin/casdoor/issues/2205

feat: make MFA works for CAS login

---

web/src/App.js
web/src/auth/LoginPage.js

feat: fix login page path after logout

---

web/src/App.js
web/src/auth/LoginPage.js

feat: Revert "feat: fix login page path after logout"

---

ldap/server.go
ldap/util.go

Fix: https://github.com/casbin/casdoor/issues/2572

feat: more RFC like LDAP server behaviour

---

controllers/casbin_api.go

Add support for enforce and batchEnforce by owner in Casbin API

fix: support owner parameter in enforce API

---

.github/workflows/build.yml

fixes https://github.com/casdoor/casdoor-helm/issues/3

fix(ci): fix the helm publish step

---

object/token_jwt.go

Continue: https://github.com/casbin/casdoor/commit/b118a3bb762d49d3a39c3695daaf25a95d854c42
Fix: https://github.com/casbin/casdoor/issues/2577

feat: support "JWT-Custom" to customize user properties inside access token

---

go.mod
go.sum
storage/storage.go
storage/synology_nas.go
web/src/ProviderEditPage.js
web/src/Setting.js

Fix: https://github.com/casbin/casdoor/issues/2049

feat: add Synology NAS storage provider

---

web/src/auth/mfa/MfaVerifyTotpForm.js
web/src/common/SendCodeInput.js

Fix: https://github.com/casbin/casdoor/issues/2637
Fix: https://github.com/casbin/casdoor/issues/2638

feat: fix autoComplete for MFA passcode and SMS code

---

web/src/UserEditPage.js
web/src/auth/MfaSetupPage.js

Fix: https://github.com/casbin/casdoor/issues/2631

feat: improve MFA UI and jump URL

---

object/syncer_util.go
object/token_jwt.go
object/user.go
object/user_upload.go
swagger/swagger.json
swagger/swagger.yml
web/src/Setting.js
web/src/UserEditPage.js
web/src/WebhookEditPage.js

Fix https://github.com/casbin/casdoor/issues/2651
**How was it Tested?**
- Ran webserver on macos
- `make deps` to spin up database
- Used VScode to spin up golang debugger
- Sent requests using website to update user's isDeleted toggle
- Network payload showed field is correctly set
- Connected DB with DBBeaver Application to confirm field is properly set
**Screenshots**

feat: add deletedTime to user

---

controllers/auth.go
controllers/casbin_api.go
controllers/system_info.go
idp/wechat.go
util/path.go
util/setting.go
util/system.go
util/system_test.go

Fix: https://github.com/casbin/casdoor/issues/2663
replace io/ioutils pacakage with io/os package

fix: improve code format

---

object/mfa_sms.go
object/mfa_totp.go
web/src/App.js

feat: fix missing MFA session issue

---

controllers/mfa.go
controllers/verification.go
object/mfa.go
object/mfa_sms.go
object/mfa_totp.go
web/src/auth/MfaSetupPage.js

feat: refactor MFA code and fix no-session bug

---

object/application.go
web/src/auth/LoginPage.js
web/src/auth/ProviderButton.js
web/src/auth/SignupPage.js
web/src/table/SigninTable.js

fix: fix display bug in SigninTable

---

object/application.go
web/src/auth/LoginPage.js
web/src/auth/ProviderButton.js
web/src/auth/SignupPage.js
web/src/table/SigninTable.js

fix: Revert "fix: fix display bug in SigninTable"

---

controllers/mfa.go
object/mfa_sms.go

feat: fix issue that admin cannot enable MFA for user

---

object/token.go

Phone Number supports for /api/login/oauth/access_token as username
✅ Closes: #2724

feat: support phone and Email in /api/login/oauth/access_token API

---

web/package.json
web/src/i18n.js
web/yarn.lock

feat: revert "feat: use i18next-resources-to-backend to lazy load i18n"

---

web/src/Setting.js
web/src/auth/ForgetPage.js
web/src/auth/LoginPage.js
web/src/auth/ResultPage.js
web/src/auth/SignupPage.js

fix: #2596 
use route to redirect

feat: use React routing to remove spin between signup and signin pages

---

web/src/App.js

fix: theme will set to default after flush

fix: theme will fully restore after page reload

---

web/src/App.js
web/src/ManagementPage.js

feat: separate management page from app.js and use lazy load to import it , and successfully reduce the size of entry page to 1.4MB when gzip is enable

fix: refactor out ManagementPage.js from App.js

---

web/src/App.js
web/src/auth/SelfLoginPage.js

feat: use lazy load to load management pages and load directly when using SelfLoginPage

feat: use lazy load to load management pages

---

web/src/i18n.js

feat: use resourcesToBackend to load i18n files

feat: use resourcesToBackend to load i18n files

---

controllers/transaction.go
object/ormer.go
routers/router.go
web/src/ManagementPage.js
web/src/TransactionEditPage.js
web/src/TransactionListPage.js
web/src/backend/TransactionBackend.js
web/src/locales/ar/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

Fix: https://github.com/casdoor/casdoor/issues/2758
feat: add basic crud controller, frontend pages and necessary translations for transaction.

feat: add transaction pages

---

object/application.go

fix: add missing / for style tag in signin items

---

web/src/basic/CustomHead.js

fix: fix duplicate load of custom head

fix: fix duplicated load bug of custom JS

---

web/src/basic/CustomHead.js

fix: fix custom head will not reload when refresh

feat: fix custom JS doesn't reload after refresh bug

---

web/src/auth/ProviderButton.js
web/src/auth/Util.js
web/src/common/OAuthWidget.js

fix: fix wechat media account can not bind

fix: fix wechat media account can not bind issue

---

web/src/Setting.js
web/src/auth/AuthCallback.js

fix: callback will jump to blank page when from param start with "http"

feat: callback will jump to blank page when from param start with "http"

---

web/src/UserEditPage.js

fix: fix account items display error
**before** 
**now**

fix: fix account items display error

---

web/src/App.js

fix: remove loading fallback in Suspense and use spin to display

feat: remove loading fallback in Suspense and use spin to display

---

web/src/auth/ForgetPage.js

fix: forget password fail to redirect back to signin page

feat: fix issue that forget password page fails to redirect back to signin page

---

object/cert.go
object/token_jwt_key.go
object/token_jwt_key_test.go
web/src/CertEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/2751

fix: add more cert algorithms like ES256 and PS256

---

web/src/auth/LoginPage.js

feat: improve organization select page

feat: improve organization select UI

---

object/saml_idp.go

Fix: https://github.com/casdoor/casdoor/issues/2784

fix: fix the issue of adding xmlns="" when generating XML

---

controllers/auth.go
form/auth.go
object/application.go
object/user.go
object/user_util.go
object/verification.go
web/package.json
web/src/ApplicationEditPage.js
web/src/Setting.js
web/src/UserEditPage.js
web/src/auth/LoginPage.js
web/src/common/modal/FaceRecognitionModal.js
web/src/table/AccountTable.js
web/src/table/FaceIdTable.js
web/src/table/SigninMethodTable.js
web/yarn.lock

Fix: https://github.com/casdoor/casdoor/issues/2537
Face Login via face-api.js

feat: add "Face ID" login method

---

web/craco.config.js

fix: "fs" module not found issue in face-api.js for browser usage

---

authz/authz.go
controllers/face.go
routers/router.go
web/src/auth/LoginPage.js
web/src/locales/ar/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

add FaceIdSigninBegin() to verify user information before face login

fix: add FaceIdSigninBegin() to verify user information before face login

---

util/validation.go

fix: delete duplicate err check in utils/validation.go

---

controllers/account.go
controllers/auth.go
main.go
object/record.go
routers/authz_filter.go
routers/record.go
web/src/RecordListPage.js
web/src/locales/ar/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

Fix: https://github.com/casdoor/casdoor/issues/2795

feat: add response to Records page

---

web/src/App.js

Fix: https://github.com/casdoor/casdoor/issues/2766

feat: can specify UI theme via `/?theme=default` and `/?theme=dark`

---

web/src/auth/ForgetPage.js

Fix: https://github.com/casdoor/casdoor/issues/2785

feat: add back button in forget password page

---

controllers/provider.go

fix: admin in other org can modify shared provider and provider belongs to another org

fix: fix permission problem in provider

---

web/src/App.js
web/src/EntryPage.js

Fix: https://github.com/casdoor/casdoor/issues/2691

feat: Google One Tap should be hidden after logged in

---

Dockerfile

Add tzdata to resolve possible time zone errors

feat: add tzdata package in Dockerfile to fix timezone issue

---

web/package.json
web/yarn.lock

fix: #2860 
this issue is cause by difference version of cssinjs added in project and dependent on antd

feat: degrade the ant-design/cssinjs version to fix the Chrome 87 broken UI issue

---

object/application.go
web/src/auth/LoginPage.js
web/src/table/SigninTable.js

fix: fix customCss will empty when add new signinItem and fix display error of back button

feat: fix empty custom CSS for new rows in signin items table

---

web/src/auth/ProviderButton.js

fix: when using big icon mode, custom oauth and saml provider in login page will submit form

feat: fix error behavior of custom oauth/saml provider in login page in big icon mode

---

routers/static_filter.go

Fix: https://github.com/casdoor/casdoor/issues/2910

feat: fix Auto-login causing AuthCodeWithPKCE Failures

---

object/init_data.go

feat: fix bug that fails to import built-in org via init_data.json

---

object/record.go

Fix: https://github.com/casdoor/casdoor/issues/2919

feat: improve record content masking

---

go.mod
go.sum
object/sms.go
web/src/ProviderEditPage.js
web/src/Setting.js

Fix: https://github.com/casdoor/casdoor/issues/2895

feat: add sms provider sendcloud

---

object/group.go
object/init_data.go
object/permission.go
object/role.go
object/user.go

fix: #2928
@ladung can you help me to test this?

feat: fix potential bugs in init_data.go

---

object/syncer.go

feat: fix password not updated bug when updating syncer

---

controllers/user.go
object/user.go
object/user_util.go

Fix: https://github.com/casdoor/casdoor/issues/2939

feat: use lowercase username when isUsernameLowered is enabled

---

object/application.go
web/src/auth/LoginPage.js
web/src/table/SigninTable.js

Fix: https://github.com/casdoor/casdoor/issues/2947

feat: support "label" field for signin item table

---

web/src/auth/SignupPage.js

Fix: https://github.com/casdoor/casdoor/issues/2957

feat: check signup item email regex in signup page

---

idp/google.go
object/provider.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js
web/src/locales/ar/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

Fix: https://github.com/casdoor/casdoor/issues/2954

feat: get phone number and country from Google OAuth provider

---

web/src/auth/Provider.js

Fix: https://github.com/casdoor/casdoor/issues/2959

feat: fix QQ login error when using mobile browser

---

controllers/service.go
web/src/common/TestEmailWidget.js

Fix: https://github.com/casdoor/casdoor/issues/2976

feat: test SMTP connection with browser parameters

---

controllers/user.go

fix: #2982
sorry for the close pr of @KoiraCMT

feat: fix password not encrypted issue in SetPassword() API

---

Dockerfile

feat: fix cannot create "/files" folder issue in local file storage provider in Docker

---

Dockerfile

feat: Revert "feat: fix cannot create "/files" folder issue in local file storage provider in Docker"

---

object/token_jwt.go

feat: Revert "feat: fix OIDC address field"

---

routers/authz_filter.go
routers/base.go

ref https://github.com/casdoor/casdoor/pull/1971
Fix: https://github.com/casdoor/casdoor/issues/3023
It's currently not possible to authenticate by Access key and Access secret if there is no session set with an empty username

feat: fix bug for access key and secret login

---

controllers/token.go
object/token_jwt.go
object/token_oauth.go
object/token_standard_jwt.go
web/src/ApplicationEditPage.js

fix: #3001
add a new jwt format to provide standard OIDC JWT to solve address type problem
use https://github.com/Timshel/vaultwarden/issues/65 to test and successfully signin

feat: add JWT-Standard format to fix oidc address type problem

---

object/payment.go
object/product.go
object/provider.go
object/transaction.go
object/user.go
pp/balance.go
web/src/PaymentResultPage.js
web/src/ProviderEditPage.js
web/src/Setting.js

feat: link transaction with balance and payment

---

web/src/WebhookEditPage.js

feat: add webhook support for invoice-payment and notify-payment

feat: add webhook support for invoice-payment and notify-payment

---

ldap/util.go

Fix: https://github.com/casdoor/casdoor/issues/3042

feat: Allow All Users to Perform LDAP Search Lookups in their org

---

ldap/server.go
ldap/util.go

Fix: https://github.com/casdoor/casdoor/issues/3067

feat: Add Support for `memberOf` Overlay in LDAP Server

---

idp/lark.go

Fix: https://github.com/casdoor/casdoor/issues/3074

feat: improve name mapping in LarkIdProvider

---

object/organization.go

fix: #3073 
@SidneySun may be this pr can solve your problem, can you help me to test?

feat: fix missing extendApplicationWithSigninMethods() in getDefaultApplication()

---

web/src/auth/Provider.js

Fix: https://github.com/casdoor/casdoor/issues/2937

feat: update WeCom OAuth URLs (#2937)

---

util/string.go

Hello! 
This pr is the same purpose of #2660 , but for the /api/batch-enforce endpoint.

feat: ABAC support for /api/batch-enforce endpoint

---

controllers/auth.go

feat: fix bug that user can signup without invitation code via OAuth

---

web/src/InvitationEditPage.js

fix: fix application field in invitationEditPage will use translation of "All" as value

fix: fix application field in invitationEditPage will use translation of "All" as value

---

web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

Fix: https://github.com/casdoor/casdoor/issues/2975

feat: enforce acceptance of terms and conditions for social logins

---

radius/server.go

Fix: https://github.com/casdoor/casdoor/issues/2979

feat: support Radius Challenge/Response for MFA (RFC2865) feature request

---

go.mod
go.sum
routers/base.go

Fix: https://github.com/casdoor/casdoor/issues/3060

feat: fix Beego session delete concurrent issue

---

object/token_jwt.go
web/src/ApplicationEditPage.js

fix: fix jwt generate cause by shared application

feat: fix JWT generate issue cause by shared application

---

routers/auto_signin_filter.go

feat: support accessKey and accessSecret login in AutoSigninFilter

---

captcha/provider.go
web/src/Setting.js
web/src/common/CaptchaWidget.js

feat: Revert "feat: support reCAPTCHA v3 captcha provider"

---

controllers/user.go

feat: Ensure MFA email and phone are validated before enabling

---

deployment/deploy.go
go.mod
go.sum
object/storage.go
storage/casdoor.go
storage/storage.go
web/src/ProviderEditPage.js
web/src/Setting.js

Fix: https://github.com/casdoor/casdoor/issues/3142

feat: support Casdoor storage provider

---

object/application.go
object/oidc_discovery.go
object/token_jwt.go
web/src/ApplicationEditPage.js
web/src/locales/ar/data.json
web/src/locales/cs/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sk/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

Fix: https://github.com/casdoor/casdoor/issues/3139

feat: add more crypto algorithm for jwt signing

---

routers/static_filter.go

feat: fix nonce not parsed issue in fastAutoSignin()

---

object/token_standard_jwt.go

Fix: https://github.com/casdoor/casdoor/issues/3155

feat: add email_verified, phone_number and phone_number_verified field for standard jwt token

---

routers/auto_signin_filter.go

feat: when using basic auth to fetch access_token will return restful response to oidc client

---

object/application.go

feat: fix bug that custom SAML providers are removed by GetMaskedApplication()

---

object/check.go

feat: Revert "feat: Users added through LDAP cannot log in using the set password"

---

web/src/UserEditPage.js
web/src/table/AccountTable.js
web/src/table/MfaAccountTable.js

Part of: https://github.com/casdoor/casdoor-app/issues/25

feat: support QR login for casdoor app

---

web/src/auth/CasLogout.js

fix: https://github.com/casdoor/casdoor/issues/3159

feat: fix CAS logout failure caused by Beego session update problem

---

routers/cors_filter.go

feat: fix CORS issue of /api/acs for SAML IdP

---

object/organization.go
object/user_util.go

fix: https://github.com/casdoor/casdoor/issues/3192

feat: handle null account item issue in CheckPermissionForUpdateUser()

---

object/user.go

fix: https://github.com/casdoor/casdoor/issues/3204

feat: make Organization.EnableSoftDeletion and User.IsDeleted work

---

object/application.go
object/saml_idp.go
object/token_cas.go
web/src/ApplicationEditPage.js

feat: add application.UseEmailAsSamlNameId field for SAML

---

web/src/CasbinEditor.js
web/src/IframeEditor.js
web/src/ModelEditPage.js
web/src/index.css

Fix: https://github.com/casbin/casbin-editor/issues/151

feat: support advanced editor in model edit page

---

controllers/organization.go
object/organization.go

Organizations page is count error

feat: fix organization pagination count error

---

Dockerfile

feat: fix permission problem in standard image

---

Dockerfile

feat: Revert "feat: fix permission problem in standard image"

---

web/src/UserEditPage.js
web/src/table/MfaAccountTable.js

Part of casdoor/casdoor-app#25

feat: improve QR code for casdoor-app

---

authz/authz.go
controllers/oidc_discovery.go
object/oidc_discovery.go
routers/router.go

Fixes #3243, adds [WebFinger](https://www.rfc-editor.org/rfc/rfc7033#section-3.1) support.

feat: add OIDC WebFinger support

---

idp/alipay.go

feat: fix UTF-8 charset for Alipay IdP

---

web/src/Setting.js
web/src/auth/LoginPage.js
web/src/table/SigninMethodTable.js

Fix: https://github.com/casdoor/casdoor/issues/3255
https://github.com/user-attachments/assets/26567ae2-67e2-4ced-977a-32bc251cf55f

feat: add Hide-Password option for signin method rule field

---

object/init_data.go

This will allow the user to specify accontItems in init_data, and if they don't, then it will use the default values.

feat: better handling of organization.AccountItems on init_data import

---

controllers/account.go
web/src/InvitationEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3265
demo
https://github.com/user-attachments/assets/b105a8c5-61d9-4e77-a054-19a3e3f772bc

feat: support initial group assignment for new invited users via invitation.SignupGroup field

---

web/src/auth/mfa/MfaAuthVerifyForm.js
web/src/locales/ar/data.json
web/src/locales/cs/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sk/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

feat: fix MFA's i18n error

---

web/src/auth/LoginPage.js

fix: https://github.com/casdoor/casdoor/issues/3279

feat: add getCaptchaRule() to fix bug

---

web/src/ApplicationEditPage.js
web/src/Setting.js
web/src/auth/LoginPage.js
web/src/auth/SignupPage.js

pc demo video:
https://github.com/user-attachments/assets/1a4914ec-10e6-4c66-b8ee-08a0c75ff3de
mobile demo video:
https://github.com/user-attachments/assets/ff0af0d3-ac7a-4f22-b83c-84114722cefb

feat: support ".login-panel-dark" CSS for signup/login pages

---

web/src/auth/mfa/MfaAuthVerifyForm.js
web/src/locales/ar/data.json
web/src/locales/cs/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sk/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

feat: improve MFA desc text

---

controllers/product.go
object/product.go

fix: buy product can use balance without login

feat: only admin can specify user in BuyProduct()

---

conf/app.conf
object/init_data.go

Fix: https://github.com/casdoor/casdoor/issues/3292

feat: add initDataNewOnly to app.conf to skip overriding existing data in initDataFromFile()

---

controllers/user.go
controllers/verification.go

feat: fix bug in SetPassword() API

---

web/src/auth/LoginPage.js

feat: pass signin method to CAS login to fix bug

---

.github/workflows/build.yml

Fix: https://github.com/casdoor/casdoor/actions/runs/11813996003/job/32912687806

feat: update github token to fix CI cannot release issue

---

object/saml_idp.go
web/src/ApplicationEditPage.js

fix: #3148
maybe this pr can solve this issue

feat: fix SAML metadata URL and XML generation issue when enablePostBinding is enabled

---

web/src/ManagementPage.js

feat: fix the dashboard page shows zero data in mobile phone

---

web/src/auth/LoginPage.js

feat: fix placeholder bug in signin page

---

controllers/user.go
object/check.go
object/check_password_expired.go
object/user.go
web/src/UserEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3330

feat: Force users to change their passwords after 3/6/12 months

---

web/src/auth/LoginPage.js

fix: fix saml fail to redirect when login api return RequiredMfa

feat: fix SAML failed to redirect issue when login api returns RequiredMfa

---

controllers/mfa.go

fix: error name of countryCode
SMS mfa has tested, this should be the final pr for stateless mfa

feat: fix countryCode param bug in MFA login

---

go.mod
go.sum

feat: update go sms sender

---

web/src/ProductBuyPage.js
web/src/ProductEditPage.js
web/src/Setting.js
web/src/locales/en/data.json
web/src/locales/zh/data.json

Part of: https://github.com/casdoor/casdoor/issues/3325

feat: support most popular currencies

---

web/src/App.js
web/src/Conf.js
web/src/ManagementPage.js

fix: #3371 
https://github.com/casdoor/casdoor/issues/3371#issuecomment-2499379833

feat: add AiAssistantUrl to frontend config

---

controllers/user.go
go.mod
object/check.go
object/ldap_conn.go
object/token_oauth.go

Fix: https://github.com/casdoor/casdoor/issues/3392

feat: support LDAP's SetPassword

---

object/record.go

feat: fix record's password regex bug

---

idp/github.go

Fix: https://github.com/casdoor/casdoor/issues/3089#issuecomment-2530142387

feat: get github user email with `user/emails` api

---

web/src/IframeEditor.js

fix: https://github.com/casdoor/casdoor/issues/3429

feat: advanced model editor should support changing UI language

---

object/verification.go

feat: fix VerificationRecord.IsUsed JSON Field Mapping

---

storage/storage.go
web/src/ProviderEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3432

feat: Make MinIO storage provider region setting configurable

---

object/get-dashboard.go

Part of: https://github.com/casdoor/casdoor/issues/3455
second optimize, only check 30 days data

feat: speed up GetDashboard() by only fetching last 30 days data

---

idp/github.go

Fix: https://github.com/casdoor/casdoor/issues/3459

feat: improve the error message of GitHub OAuth provider

---

object/user.go
web/src/table/MfaAccountTable.js

Part of: casdoor/casdoor-app#41

feat: add origin field for mfaAccountTable

---

controllers/auth.go
object/email.go
object/provider.go
web/src/ProviderEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3461
demo img

feat: add regex to restrict Email addresses in OAuth provider

---

object/token_oauth.go

feat: fix empty scope bug in RefreshToken API

---

idp/github.go

fix: github idp will stop login if it cannot fetch user's email

feat: fix bug that GitHub oauth provider shows error if failed to fetch user's email 

---

object/get-dashboard.go

Fix: https://github.com/casdoor/casdoor/issues/3473
fix: return error cause by goroutine in get-dashboard

feat: return goroutine error in get-dashboard API

---

util/process.go

fix https://github.com/casdoor/casdoor/issues/3482

feat: getPidByPort() supports alpine now

---

controllers/user.go
controllers/util.go

fix: #3487
to many column will slow down count speed when using mysql

feat: skip GetUserCount() if there is no quota limit

---

web/src/InvitationEditPage.js

feat: show error message when organization doesn't have default application in invitation edit page

---

object/user.go

fix: #3487 
@AtCliffUnderline can you help me to test if this pr work for you?

feat: skip update user ranking if ranking not in accountItem

---

go.mod
go.sum
notification/cucloud.go
notification/provider.go
object/notification.go
web/src/ProviderEditPage.js
web/src/Setting.js

Fix: https://github.com/casdoor/casdoor/issues/3409

feat: support CUCloud SMN notification provider

---

routers/theme_filter.go

fix: fix application theme is ignored during append theme cookie

feat: fix issue that application theme is ignored in appendThemeCookie()

---

routers/theme_filter.go
web/src/App.js

feat: append logo url to cookie
https://github.com/user-attachments/assets/ddfe5b0e-336c-476d-8b82-fb7a2d2ea5a6

feat: append logo url to cookie

---

routers/theme_filter.go
web/src/App.js

feat: append footerHtml to cookie

feat: append footerHtml to cookie

---

web/src/EntryPage.js

fix: spin will squeeze login panel
before
https://github.com/user-attachments/assets/5f2af816-6049-4686-9fb4-fcafade2e966
now
https://github.com/user-attachments/assets/99259bfe-a97c-43ce-ade3-5e15923ed86e

fix: spin will squeeze login panel

---

object/ldap.go
object/ldap_conn.go
object/ldap_password_type.go
web/src/LdapEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3497
thanks for the raw pr pull by @nanoguo
part1, part2 will try to support normal user reset password with oldpassword and newpassword

feat: can reset LDAP password with different password encryption methods

---

controllers/user.go
object/ldap_conn.go
web/src/common/modal/PasswordModal.js

feat: support user reset password with old password and new password
https://github.com/user-attachments/assets/81f4e1b4-2cbb-46b4-809b-ed12f0346448
now user can reset password with oldPassword, and reset password by user will use default encrypt method set by ldap server

feat: LDAP user can reset password with old password and new password

---

routers/static_filter.go
routers/theme_filter.go

feat: append HTML document title and favicon to cookie

---

controllers/auth.go
web/src/auth/LoginPage.js
web/src/auth/mfa/MfaAuthVerifyForm.js

fix: #3423
It seems to be more complicated

feat: allow user use other mfaType in mfa step and skip redundant MFA verification

---

web/src/auth/mfa/MfaEnableForm.js

fix: fix recovery code not pass to enable api

feat: fix missing param recoveryCodes in /mfa/setup/enable API

---

object/application.go
object/organization.go
routers/theme_filter.go

feat: fix theme filter for other URLs like SAML

---

object/user.go

feat: delete groups for user while deleting user

---

controllers/group.go
object/group.go
web/src/GroupListPage.js

fix: #3517 
@lqa0408 can you help me to test?

feat: optimize get-groups API and GroupListPage

---

web/src/auth/ForgetPage.js

feat: fix strange "Email is invalid" error in forget password page

---

controllers/auth.go
form/auth.go
routers/static_filter.go
web/src/App.js
web/src/Setting.js
web/src/auth/AuthCallback.js
web/src/auth/LoginPage.js
web/src/auth/SamlCallback.js

Fix: https://github.com/casdoor/casdoor/issues/3528

feat: can verify OTP during OAuth login

---

controllers/casbin_cli_api.go

fix: https://github.com/casdoor/casdoor/issues/3534

feat: add identifier validation for security in RunCasbinCommand

---

object/token.go

feat: fix bug in GetTokenByTokenValue()

---

object/user.go

feat: fix bug that can not delete user if user doesn't belong to any group

---

object/saml_sp.go
web/src/auth/ProviderButton.js

feat: show SAML cert parse error better in frontend

---

util/validation.go
web/src/common/CasdoorAppConnector.js

Part of: casdoor/casdoor-authenticator#52

feat: rename Casdoor app URL to authenticator

---

web/src/ProviderEditPage.js

feat: support fetch metadata from url
https://github.com/user-attachments/assets/757b551a-bbae-4028-ac16-8bbd28e5cc9a

feat: can fetch SAML metadata from URL

---

authz/authz.go
controllers/casbin_cli_api.go
controllers/cli_downloader.go
main.go

fix: https://github.com/casbin/casbin-editor/issues/230

feat: add CLI version cache and proxy support

---

routers/theme_filter.go

feat: cache theme in signup page

feat: cache theme in signup page

---

controllers/auth.go

fix: forbidden check will be skip while login with oauth

feat: fix bug that user forbidden check will be skipped in OAuth login

---

web/src/BaseListPage.js
web/src/RecordListPage.js
web/src/TokenListPage.js
web/src/common/Editor.js
web/src/locales/en/data.json
web/src/locales/zh/data.json

[Demo](https://casdoor.dev.leviatan.cn)
Username: admin
Password: 123

feat: add detail sidebar for record list page, improve token list page

---

ldap/util.go
object/group.go

feat: fix LDAP filter condition will return nil if error happened

---

object/group.go
web/src/GroupListPage.js

Fix: https://github.com/casdoor/casdoor/issues/3606

feat: fix bug that group.HaveChildren is never set to false bug Something isn't working

---

object/oidc_discovery.go

feat: set frontend origin to 7001 if in dev mode

---

controllers/verification.go
object/verification.go

Reverts casdoor/casdoor#3616
Fix: https://github.com/casdoor/casdoor/issues/3625

feat: fix MFA bug, revert PR: "feat: don't send verification code if failed signin limit is reached"

---

controllers/auth.go
form/auth.go
web/src/auth/LoginPage.js
web/src/common/select/LanguageSelect.js

[Demo](https://casdoor.dev.leviatan.cn)
Username: `admin`
Password: `123`
fixed #3548

feat: update user language when the language changed on login page

---

object/application.go
web/src/ApplicationEditPage.js
web/src/EntryPage.js

Fix: https://github.com/casdoor/casdoor/issues/3624

feat: support mobile background for login page

---

controllers/account.go
object/application.go
web/src/ApplicationEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3546

feat: can assign default group during signup

---

object/webhook.go
object/webhook_util.go
web/src/WebhookEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3605

feat: can specify user fields in webhook edit page

---

object/webhook_util.go

feat: fix webhook bug in RecordEx JSON

---

web/src/common/modal/FaceRecognitionModal.js
web/src/table/FaceIdTable.js

Fix: https://github.com/casdoor/casdoor/issues/3636
@rmsto can you help me to test this pr?
Why I add upload image in `FaceRecognitionModal.js`? To avoid load model twice

feat: can add faceId by uploading images

---

web/src/common/TestEmailWidget.js
web/src/common/TestNotificationWidget.js
web/src/common/TestSmsWidget.js

Fix: https://github.com/casdoor/casdoor/issues/3654

feat: fix provider test API's missing owner and name args for auth

---

object/adapter.go

feat: fix bug that there is already an object named 'casbin_api_rule' in the database

---

controllers/user.go

feat: fix MFA + LDAP bug in /check-user-password API

---

controllers/account.go
controllers/auth.go
controllers/verification.go
object/mfa_sms.go

feat: fix issue that user email is still unverified after signup

---

web/src/auth/LoginPage.js

feat: login button will display loading circle during login
https://github.com/user-attachments/assets/d6559ce5-ec40-4cb3-83c9-5debf42cdaa5

feat: support login button loading state

---

web/src/auth/LoginPage.js

Fix: https://github.com/casdoor/casdoor/issues/3655
https://github.com/user-attachments/assets/0a333e09-f2ed-4e57-8536-d98424b65b11
@topgun100 is this what you want ?

feat: can use provider_hint arg to do OAuth redirect automatically

---

controllers/token.go
go.mod
go.sum
object/saml_idp.go
object/token_jwt.go
object/token_standard_jwt.go

1. https://github.com/golang-jwt/jwt/security/advisories/GHSA-mh63-6h87-95cp
2. https://github.com/golang-jwt/jwt/security/advisories/GHSA-29wx-vh33-7x7r

feat: update `github.com/golang-jwt/jwt` dependency to v5

---

object/ldap.go
object/ldap_conn.go
web/src/LdapEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3701

feat: Casdoor's LDAP client supports LDAP server's self-signed certificates now

---

object/user.go

feat: fix bug that unable to query webauthnCredentials when db is mssql or postgres in GetUserByWebauthID()

---

controllers/token.go

feat: return "Active: false" for expired token in IntrospectToken()

---

controllers/token.go

enhance: #3711
Validation in case of application with token type "JWT Custom", if not all the standard token fields are present.

feat: add validation for optional fields in IntrospectionToken for custom token types

---

idp/dingtalk.go
idp/wechat.go
object/ormer.go

feat: fix code comment typos

---

web/src/ApplicationEditPage.js
web/src/auth/ForgetPage.js

feat: support application.formCss in forget-password page

---

web/src/auth/LoginPage.js

feat: fix loading status not reset issue when failed to login

---

web/src/auth/LoginPage.js

fix: handle err throw by webauthn

feat: improve error handling of webauthn login

---

object/record.go
object/webhook.go
web/src/WebhookEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3644

feat: add object field filter for webhook

---

object/cert.go
object/oidc_discovery.go

Fix: https://github.com/casdoor/casdoor/issues/3748

feat: allow jwks to include the certs from non-admin owner

---

object/group.go
util/string.go

Fix: https://github.com/casdoor/casdoor/issues/3752

feat: improve checkGroupName()

---

object/ormer.go

feat: fix bug that db not found error in createDatabaseForPostgres

---

controllers/auth.go
object/token_jwt.go
object/token_oauth.go
object/token_standard_jwt.go
routers/static_filter.go
web/src/ApplicationEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3754

feat: add logged-in IDP provider info to access token

---

web/src/Setting.js

feat: fix MFA preference doesn't work bug

---

object/user.go

feat: fix bug that username will be random with useEmailAsUsername enabled

---

controllers/token.go

feat: fix access_token endpoint cannot read clientId in form when using device code flow

---

controllers/token.go

feat: return HTTP status 400 instead of 200 in GetOAuthToken()

---

controllers/token.go
controllers/util.go

feat: fix bug that token endpoint doesn't return 400/401 when type is object.TokenError

---

object/token_jwt.go
object/token_standard_jwt.go

fix: #3806 
@maggch97 can you pull this repo and help me test this pr? You need to set Token format to JWT-Standard first.

feat: use the standard user struct for JWT-Standard to get a correct userinfo

---

web/src/auth/AuthCallback.js
web/src/auth/PromptPage.js
web/src/auth/SignupPage.js

Replace: https://github.com/casdoor/casdoor/pull/3794

feat: can redirect user to login page after linking provider in prompt page

---

idp/goth.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

feat: can configure Domain field in Nextcloud OAuth provider

---

web/src/auth/AuthBackend.js

Fix: https://github.com/casdoor/casdoor/issues/3819

feat: support special chars like "+" in username parameter of /api/get-email-and-phone API

---

controllers/group.go
object/group.go

feat: fix GetGroups() API bug when parentGroup is in next page

---

controllers/auth.go

feat: Add support for email verification logic

---

captcha/aliyun.go
captcha/default.go
captcha/geetest.go
captcha/hcaptcha.go
captcha/provider.go
captcha/recaptcha.go
captcha/turnstile.go
controllers/auth.go
controllers/verification.go
go.mod
web/src/ProviderEditPage.js
web/src/common/CaptchaWidget.js
web/src/common/modal/CaptchaModal.js

Fix: https://github.com/casdoor/casdoor/issues/3827

feat: upgrade Alibaba cloud captcha provider from v1 to v2

---

web/src/common/CaptchaWidget.js

fix: remove support for Non trace verification for aliyun verification

feat: remove support for Non trace verification for Alibaba cloud captcha verification 

---

controllers/user.go
object/user.go
object/user_util.go

Fix: https://github.com/casdoor/casdoor/issues/3880

feat: get-user API respects org's account item's view rules now

---

main.go
routers/field_validation_filter.go

feat: add FieldValidationFilter to check object names

---

web/src/ApplicationEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/3883

feat: improve error message in ApplicationEditPage

---

controllers/product.go

Fix: https://github.com/casdoor/casdoor/issues/3896

feat: fix check bug to allow logged-in users to buy product

---

object/token_cleanup.go

Fix bug in: https://github.com/casdoor/casdoor/pull/3903

feat: fix bug in InitCleanupTokens()

---

web/src/auth/mfa/MfaVerifyTotpForm.js

feat: use Input.OTP to input totp code
https://github.com/user-attachments/assets/20ba6bff-8792-4942-9db8-1b7bfbb6ac9d

feat: use Input.OTP to input totp code

---

controllers/user.go
cred/argon2id.go
cred/bcrypt.go
cred/manager.go
cred/md5-user-salt.go
cred/pbkdf2-salt.go
cred/pbkdf2_django.go
cred/plain.go
cred/sha256-salt.go
cred/sha256-salt_test.go
cred/sha512-salt.go
object/organization.go
object/user_cred.go

Fix: https://github.com/casdoor/casdoor/issues/3901

feat: CredManager.GetHashedPassword() only contains one salt arg now

---

object/check.go

Fix: #3902
Continue of #3937; That PR is closed due to rebase to resolve conflict with the recently merged #3936.
1. Original code logic is not changed
2. Rebased from #3936 and solved conflict with it
3. Fixed the missing update of `PasswordSalt`as mentioned by @dacongda in #3937

feat: Supports smooth migration of password hash

---

controllers/service.go
controllers/verification.go
object/verification.go
web/src/ProviderEditPage.js
web/src/Setting.js
web/src/auth/ForgetPage.js

Fix: https://github.com/casdoor/casdoor/issues/3673

feat: support links in email to reset password

---

idp/lark.go
idp/provider.go
web/src/ProviderEditPage.js
web/src/auth/Provider.js

Fix: https://github.com/casdoor/casdoor/issues/3953
demo:
https://github.com/user-attachments/assets/452a012f-3c8e-4ed4-b060-40176617084c

feat: add Lark OAuth provider

---

web/src/auth/LoginPage.js
web/src/common/modal/CaptchaModal.js
web/src/table/SigninTable.js

Fix: https://github.com/casdoor/casdoor/issues/3950

feat: support inline-captcha in login page

---

web/src/App.js

fix: language will be switched to user's language after refresh

feat: fix bug that language cannot be switched to user selected language

---

web/src/auth/LoginPage.js

Fix https://github.com/casdoor/casdoor/issues/3978

feat: fix bug that needUpdatePassword is not respected

---

controllers/account.go
web/src/auth/ResultPage.js

Fix: https://github.com/casdoor/casdoor/issues/3670
https://github.com/user-attachments/assets/9b41b0ed-b425-4d21-a769-a8af8b9fb816

feat: fix auto sign-in flow on result page

---

controllers/util.go
i18n/locales/ar/data.json
i18n/locales/cs/data.json
i18n/locales/de/data.json
i18n/locales/en/data.json
i18n/locales/es/data.json
i18n/locales/fa/data.json
i18n/locales/fi/data.json
i18n/locales/fr/data.json
i18n/locales/he/data.json
i18n/locales/id/data.json
i18n/locales/it/data.json
i18n/locales/ja/data.json
i18n/locales/kk/data.json
i18n/locales/ko/data.json
i18n/locales/ms/data.json
i18n/locales/nl/data.json
i18n/locales/pl/data.json
i18n/locales/pt/data.json
i18n/locales/ru/data.json
i18n/locales/sk/data.json
i18n/locales/sv/data.json
i18n/locales/tr/data.json
i18n/locales/uk/data.json
i18n/locales/vi/data.json
i18n/locales/zh/data.json
i18n/util.go
object/check_util.go

feat: make enableErrorMask work for corner cases by moving checks from controller to Translate()

---

controllers/webauthn.go
web/src/auth/LoginPage.js
web/src/backend/UserWebauthnBackend.js
web/src/table/WebauthnCredentialTable.js

fix: #3993
https://github.com/user-attachments/assets/5a1241ad-e12f-40b8-9436-2b74e900546a

feat: add back support for non-discoverable credential WebAuthn login and display WebAuthn ID again

---

controllers/cli_downloader.go

Part of: https://github.com/casbin/casbin-editor/issues/238

feat: add support for casbin-python-cli auto-download

---

ldap/server.go
ldap/util.go

fix: #3974 
@xtutu can this pr solve your issue? Due to I haven't enough conditions to deploy gitlab, so I need your assist to check

feat: fix objectClass filter will return empty response

---

ldap/server.go
ldap/util.go
object/group.go

feat: add posixAccount and posixGroup filter logic for more versatile usage in LDAP

---

web/src/auth/LoginPage.js

feat: improve error handling on signInWithWebAuthn

feat: improve error handling on signInWithWebAuthn

---

web/src/auth/LoginPage.js
web/src/auth/WeChatLoginPanel.js
web/src/table/SigninMethodTable.js

Fix: https://github.com/casdoor/casdoor/issues/3976
effect rule == Login page
effect rule == Tab

feat: support scanning code to login in the login page

---

web/src/auth/LoginPage.js

fix: fix search params lose in switchLoginOrganization

feat: fix missing search params bug in switchLoginOrganization()

---

web/src/auth/LoginPage.js

Fix: https://github.com/casdoor/casdoor/issues/3380

feat: add country code to validate phone number when Code method's rule is Phone only

---

controllers/auth.go
web/src/auth/Provider.js

fix: fix signup via provider in shared application will signup to built-in app

feat: fix issue that signing up via provider in shared application will sign up to built-in app

---

object/token_jwt.go

feat: fix bug that custom JWT token no longer includes properties

---

object/permission.go
object/permission_enforcer.go

Fix: https://github.com/casdoor/casdoor/issues/4127

feat: change builtInMaxFields to 6 in Casbin policy length

---

controllers/auth.go
object/token_jwt.go
object/token_oauth.go
routers/static_filter.go

Fix: https://github.com/casdoor/casdoor/issues/4103

feat: add signinMethod in JWT token

---

controllers/user.go
i18n/locales/ar/data.json
i18n/locales/az/data.json
i18n/locales/cs/data.json
i18n/locales/de/data.json
i18n/locales/en/data.json
i18n/locales/es/data.json
i18n/locales/fa/data.json
i18n/locales/fi/data.json
i18n/locales/fr/data.json
i18n/locales/he/data.json
i18n/locales/id/data.json
i18n/locales/it/data.json
i18n/locales/ja/data.json
i18n/locales/kk/data.json
i18n/locales/ko/data.json
i18n/locales/ms/data.json
i18n/locales/nl/data.json
i18n/locales/pl/data.json
i18n/locales/pt/data.json
i18n/locales/ru/data.json
i18n/locales/sk/data.json
i18n/locales/sv/data.json
i18n/locales/tr/data.json
i18n/locales/uk/data.json
i18n/locales/vi/data.json
i18n/locales/zh/data.json
object/check_password_complexity.go

Fix: https://github.com/casdoor/casdoor/issues/4133

feat: add password change validation to ensure new password differs from current password

---

i18n/locales/pt/data.json

This PR improves Portuguese translations by fixing untranslated strings, ensuring consistency, and polishing grammar.
Closes #4142

feat: improve pt i18n strings

---

object/token_jwt.go
web/src/ApplicationEditPage.js

Fix: https://github.com/casdoor/casdoor/issues/4094

feat: support "permissionNames" field in JWT-Custom token

---

object/init_data.go
object/init_data_dump.go

fix: #4155
this pr will also save polices to json file and load it to rule table

feat: fix Data Missing From casbin_rule Table After Importing init_data.json

---

object/application.go
web/src/basic/AppListPage.js
web/src/basic/GridCards.js
web/src/basic/SingleCard.js

Fix: https://github.com/casdoor/casdoor/issues/4151
https://github.com/user-attachments/assets/e59f65d6-5e1b-4b7b-aca9-374359efbaf0

feat: add tag filtering in app list page

---

web/src/table/SigninTable.js

feat: persist custom signin item label in signin items table

---

web/src/ProviderEditPage.js
web/src/locales/ar/data.json
web/src/locales/az/data.json
web/src/locales/cs/data.json
web/src/locales/de/data.json
web/src/locales/en/data.json
web/src/locales/es/data.json
web/src/locales/fa/data.json
web/src/locales/fi/data.json
web/src/locales/fr/data.json
web/src/locales/he/data.json
web/src/locales/id/data.json
web/src/locales/it/data.json
web/src/locales/ja/data.json
web/src/locales/kk/data.json
web/src/locales/ko/data.json
web/src/locales/ms/data.json
web/src/locales/nl/data.json
web/src/locales/pl/data.json
web/src/locales/pt/data.json
web/src/locales/ru/data.json
web/src/locales/sk/data.json
web/src/locales/sv/data.json
web/src/locales/tr/data.json
web/src/locales/uk/data.json
web/src/locales/vi/data.json
web/src/locales/zh/data.json

This change applies only to Azure AD and Azure AD B2C providers.
fix: #4178

feat: improve domain field text in provider edit page

---

object/application.go
object/saml_idp.go
object/token_jwt.go
object/user_util.go
web/src/ApplicationEditPage.js
web/src/table/TokenAttributeTable.js

Fix: https://github.com/casdoor/casdoor/issues/4168

feat: add token attribute table to provide a more flexible Jwt-custom token in application edit page

---

object/application.go
web/src/auth/LoginPage.js
web/src/common/SendCodeInput.js
web/src/table/SigninTable.js

Fix: https://github.com/casdoor/casdoor/issues/4160

feat: add code verification label in signin items

---

object/check.go

feat: check roles in CheckLoginPermission

---

object/storage.go

fixes: #4166
My config:
After I upload my avatar, the avatar photo can be displayed correctly.

feat: improve compatibility for MinIO storage provider

---

web/src/auth/SignupPage.js

feat: fix issue that couldn't auto set invitatonCode when using oAuth signup link

---

routers/authz_filter.go

feat: fix JSON parse error with ObjectWithOrg in authz_filter.go's getObject()
